### ISSUE TITLE
Should the token in the header be base64 encoded?

### ISSUE THREAD

**Issue by bojanz** [bshaffer/oauth2-server-php#100]
The spec is not clear about this, and the examples don't look encoded.
However, the spec points you to http://tools.ietf.org/html/rfc6750#section-2.1
which says:

>  The syntax of the "Authorization" header field for this scheme
>  follows the usage of the Basic scheme defined in Section 2 of
>   [RFC2617].  Note that, as with Basic, it does not conform to the
>   generic syntax defined in Section 1.2 of [RFC2617] but is compatible
>   with the general authentication framework being developed for
>   HTTP 1.1 [HTTP-AUTH], although it does not follow the preferred
>   practice outlined therein in order to reflect existing deployments.
>   The syntax for Bearer credentials is as follows:
> 
> ```
> b64token    = 1*( ALPHA / DIGIT /
>                   "-" / "." / "_" / "~" / "+" / "/" ) *"="
> ```
> 
>    credentials = "Bearer" 1*SP b64token

So does b64token in this case mean it should be encoded? It also points to Authorization: Basic where the credentials are base64 encoded.

**Comment by Kavindu-Dodan** [comment]
Doesn't it say to use base64 encoding. This phrase, "The syntax of the "Authorization" header field for this scheme follows the usage of the Basic scheme defined in Section 2 of [RFC2617]" points out to base64 encoding. As per RFC2617, Basic schema encode username password in base64 encoding.
