### ISSUE TITLE
chore: move from travis to github actions

### ISSUE THREAD

**Issue by bshaffer** [bshaffer/oauth2-server-php#1015]
Travis's body quit. Travis's bird quit. And unfortunately, Travis is no longer legit.

**Comment by trylika** [comment]
@bshaffer how is it going with this one? as it's needed for php8.1, maybe i could help in some way?

**Comment by bshaffer** [comment]
@trylika we need to move to GitHub actions. It should be very easy to do if you'd like to give it s try!

**Comment by bshaffer** [comment]
> @bshaffer can you review my efforts for migrating to github actions?:)
> 
> here are some proofs of them working https://github.com/trylika/oauth2-server-php/actions
> 

The best way for me to review is for you to submit a pull request

**Comment by trylika** [comment]
@bshaffer it's already submitted https://github.com/bshaffer/oauth2-server-php/pull/1016

**Comment by trylika** [comment]
one more update: fixed phpunit tests for php 8.0 and 8.1
this required changing minimum phpunit version to ^8.0

**Comment by bshaffer** [comment]
this has been completed!
