### ISSUE TITLE
The correct table structure

### ISSUE THREAD

**Issue by JellyBellyDev** [bshaffer/oauth2-server-php#14]
Sorry but I can not understand what is the right database structure to use!
This class OAuth2_Storage_Pdo understand that you must have 4 tables:
- oauth_clients
- oauth_access_tokens
- oauth_authorization_codes
- oauth_users
  but how they are structured? With what fields and what kind?
  Not familiar with the framework used in the demo and I can not understand the flow of the process! : S
  Thanks

**Comment by miyaotoki** [comment]
how can i know users belong to which client?
