### ISSUE TITLE
Use of user_id parameter

### ISSUE THREAD

**Issue by abeverley** [bshaffer/oauth2-server-php#152]
I can't find any documentation about using the user_id parameter. Am I missing it or does it not exist?

If it's the latter, then I'll happily add a few notes to the Readme file, if that suits? It's taken me a while to work it out.

BTW: Thanks for merging previous request - I didn't manage to work out how to resubmit within the Github web interface (next time I'll just check the code out myself!)

**Comment by frey1esm** [comment]
Can the user_id for a new token be set (i.e. stored in in the database) at the time the token is generated?

**Comment by shahabmusic** [comment]
Can the user_id be retrieved from the access token? user_id is null in my access token. how to set it?

**Comment by bshaffer** [comment]
The `user_id` is retrieved server-side from the access token, but not client-side. And it will be null if the value in the database is null.
