### ISSUE TITLE
Can't inherit

### ISSUE THREAD

**Issue by fahmiardi** [bshaffer/oauth2-server-php#161]
PHP Fatal error:  Can't inherit abstract function OAuth2\GrantType\GrantTypeInterface::validateRequest() (previously declared abstract in OAuth2\ClientAssertionType\ClientAssertionTypeInterface) in /Applications/MAMP/htdocs/oauth2/vendor/bshaffer/oauth2-server-php/src/OAuth2/GrantType/ClientCredentials.php on line 14

why I get this message, I use branch develop with namespace

**Comment by almaruf** [comment]
@bshaffer  I have this problem on PHP 5.3.8
Can't inherit abstract function OAuth2\Storage\AuthorizationCodeInterface::setAuthorizationCode() (previously declared abstract in OAuth2\OpenID\Storage\AuthorizationCodeInterface)

**Comment by bshaffer** [comment]
@almaruf the `develop` branch of this library is only compatible with php 5.3.9 and above (see the [requirements](https://github.com/bshaffer/oauth2-server-php/blob/develop/composer.json#L16)). 

Keep in mind PHP 5.3 is EOL'd and is no longer receiving security fixes. Even so, I acknowledge many people do not have the ability to upload servers for a multitude of reasons. For them, we have the [php5.2-develop](https://github.com/bshaffer/oauth2-server-php/tree/php5.2-develop) branch. 

If you need features only found in `develop`, consider extending or modifying the library to do so (i.e. copying the interface classes and removing the methods, and then ensuring your autoloader finds them first)
