### ISSUE TITLE
Allow to set scope with client_credentials grant type

### ISSUE THREAD

**Issue by mikehaertl** [bshaffer/oauth2-server-php#207]
Currently when using grant type `client_credentials`, no scopes can be used:

https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/GrantType/ClientCredentials.php#L20

I don't think, RFC 6749 enforces or even recommends this. So I'd say, we should have the same scope mechanism as for users.

**Comment by abhishekrohilla** [comment]
How do we send multiple scopes while generating token? Does the library support sending only one scope?

**Comment by abhishekrohilla** [comment]
Asked the question too soon. Got it in RFC.
 The value of the scope parameter is expressed as a list of space-
   delimited, case-sensitive strings.  The strings are defined by the
   authorization server.
