### ISSUE TITLE
UserCredentialsInterface, $client_id param

### ISSUE THREAD

**Issue by jdelaune** [bshaffer/oauth2-server-php#236]
The docs say "You can also use the $client_id param to do any checks required based on a client, if you need that."

https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/Storage/UserCredentialsInterface.php#L19

However the function only receives a username and password?

**Comment by darthtong** [comment]
Fast forward 4 years...I don't suppose after all this time this has been cleared up? The comment still exists but the code does not. I too require access to the client_id in this context.

**Comment by jahrralf** [comment]
Same here, I changed the source code to have this and need to make the same changes again and again for every update... Would be really to great to have client_ID in methods.

**Comment by bshaffer** [comment]
Do you want to submit a PR for it? You've made the changes so many times it sounds like you could submit the changes to this repository fairly quickly.
