### ISSUE TITLE
Implement 'jti' parameter for jwt to prevent replay attacks

### ISSUE THREAD

**Issue by F21** [bshaffer/oauth2-server-php#265]
The 'jti' parameter in a JWT is a nonce to prevent replay attacks. This is currently optional in the [spec](http://tools.ietf.org/html/draft-ietf-oauth-json-web-token-13#section-4.1.7) and is not currently implemented in the library.

We should add support for checking the jti to see if it has been used. If so, the request should be denied.

**Comment by Sicaine** [comment]
@F21 i'm just answering because i found it through google and someone else might find it:
I would only use uuid (in version 4). It reduces the risk of collisions to a level where i can trust it enough to generate unique ids.
