### ISSUE TITLE
"CryptoTokens" should match "JWT" spec

### ISSUE THREAD

**Issue by bshaffer** [bshaffer/oauth2-server-php#338]
CryptoToken is a word I made up. These are actually just JSON Web Tokens... why the distinction? Because I didn't know better.  Let's fix it!

**Comment by bbalet** [comment]
Please update online documentation : 
http://bshaffer.github.io/oauth2-server-php-docs/overview/crypto-tokens/

**Comment by bshaffer** [comment]
@bbalet I will as soon as the changes are merged into master for [v1.6](https://github.com/bshaffer/oauth2-server-php/pull/496)

**Comment by bshaffer** [comment]
@bbalet docs updated and release tagged
