### ISSUE TITLE
The grant type is unauthorized for this client_id

### ISSUE THREAD

**Issue by victorhqc** [bshaffer/oauth2-server-php#344]
I've been working with this server from some months now without problems, but recently I'm implementing the server to work with Laravel and everything seems to be good until the authorization grant is performed, returning the next error:

```
error=unauthorized_client&error_description=The+grant+type+is+unauthorized+for+this+client_id
```

I'm using the implicit grant using a Web Application. Maybe I'm forgetting to add something in the database, the `grant_types` column perhaps?

The code that initializes the server is the following:

```
OAuth2\Autoloader::register();

$storage = new OAuth2\Storage\Pdo(array('dsn' => "mysql:host=localhost;dbname=db", 'username' => "root", 'password' => "password"));

// Pass a storage object or array of storage objects to the OAuth2 server class
$config = array('allow_implicit' => true, 'access_lifetime' => 3600 * 24 * 7 * 3); // 3 weeks duration
$server = new OAuth2\Server($storage, $config);

// Add the "Client Credentials" grant type (it is the simplest of the grant types)
$server->addGrantType(new OAuth2\GrantType\ClientCredentials($storage));

// Add the "Authorization Code" grant type (this is where the oauth magic happens)
$server->addGrantType(new OAuth2\GrantType\AuthorizationCode($storage));
```

**Comment by johnroid** [comment]
What to do if I want **multiple grant types**  for single client id and client secret ?

**Comment by ViniciusFernan** [comment]
> What to do if I want **multiple grant types** for single client id and client secret ?

use all grand_type separated by spaces eg: "client_credentials password authorization_code refresh_token"
