### ISSUE TITLE
user_id

### ISSUE THREAD

**Issue by pjebs** [bshaffer/oauth2-server-php#366]
In the oauth_client table, there is a column for "user_id". I'm not sure what it's for. For the authorization code grant, is it safe to delete out?

**Comment by pjebs** [comment]
I am still wondering what the user_id column is for in client_credentials grant type.

If it is used in the Resource Controller Endpoint, you getAccessTokenData still gives you the client_id.

**Comment by bshaffer** [comment]
It's used to associate the client with the user who created it.

**Comment by pjebs** [comment]
For authorisation code grant type, I understand that user_id in token table helps associate the token to the client and user.

For client credentials, the user is irrelevant so I still don't understand why it's needed and why it's in client table.

GetAccessTokenData() can pull the client_id from the token anyway.

**Comment by bshaffer** [comment]
The user isn't irrelevant, client credentials still have a user context.
The client IS the user. If you don't want a user context at all, JwT bearer
is more appropriate.
