### ISSUE TITLE
User Credentials without Client Credentials not working

### ISSUE THREAD

**Issue by arianf** [bshaffer/oauth2-server-php#377]
I have been trying to get the example code from the following website to work, but have been receiving an error.

http://bshaffer.github.io/oauth2-server-php-docs/grant-types/user-credentials/ 

``` php
<?php

    // error reporting (this is a demo, after all!)
    ini_set('display_errors',1);error_reporting(E_ALL);

    require '../../../../vendor/autoload.php';

    // create some users in memory
    $users = array('bshaffer' => array('password' => 'brent123', 'first_name' => 'Brent', 'last_name' => 'Shaffer'));

    // create a storage object
    $storage = new OAuth2\Storage\Memory(array('user_credentials' => $users));

    // create the grant type
    $grantType = new OAuth2\GrantType\UserCredentials($storage);

    // Pass a storage object or array of storage objects to the OAuth2 server class
    $server = new OAuth2\Server($storage);

    // add the grant type to your OAuth server
    $server->addGrantType($grantType);

    // Handle a request for an OAuth2.0 Access Token and send the response to the client
    $server->handleTokenRequest(OAuth2\Request::createFromGlobals())->send();

```

When I try sending a curl: 

``` cmd
$ curl http://mywebsite.com/test/token.php -d 'grant_type=password&username=bshaffer&password=brent123'
```

``` json
{"error":"invalid_client","error_description":"Client credentials were not found in the headers or body"}
```

I never set client credentials, why does this require client credentials in the body?

**Comment by geeknz** [comment]
How do you declare a public client in memory? Can I use the following example? 
```php
$memStorage = new OAuth2\Storage\Memory([
	'client_credentials' => [
		'TestClient' => [ 'client_secret' => '' ]
	]
]);
```

Also is it possible to use a crypto token with user credentials? I'm having some trouble getting them working.
```php
$credentialStorage = new UserCredentials( $database );
$memStorage = new OAuth2\Storage\Memory([
    'keys' => [
        'public_key'  => file_get_contents( 'pubkey.pem' ),
        'private_key' => file_get_contents( 'privkey.pem' )
    ],
	'client_credentials' => [
		'TestClient' => [ 'client_secret' => '' ]
	]
]);
$cryptoStorage = new OAuth2\Storage\CryptoToken( $memStorage );

$server = new OAuth2\Server( $memStorage );
$server->addStorage( $cryptoStorage, 'access_token' );
$server->addStorage( $memStorage, 'client_credentials' );
$server->addGrantType( new OAuth2\GrantType\UserCredentials( $credentialStorage ) );
$server->addResponseType( new OAuth2\ResponseType\CryptoToken( $storage ) );

$server->handleTokenRequest( OAuth2\Request::createFromGlobals() )->send();
```

**Comment by justingreerbbi** [comment]
I know this topic is closed but would like to note a very likely solution to this that has not been mentioned. If the server is running using PHP CGI, then Auth basic headers will not get passed to PHP correctly thus causing this error. 

One way to check if you pass the client_id and client_secret in the body along with the username and password and the error is not there, you need to modify your .htaccess or change native PHP module.

`RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]`

**Comment by bshaffer** [comment]
@justingreerbbi thanks for pointing this out. [This line of code](https://github.com/bshaffer/oauth2-server-httpfoundation-bridge/blob/develop/src/OAuth2/HttpFoundationBridge/Request.php#L72) will also fix this issue (if you're using Apache)

A similar line exists [here](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/Request.php#L155), in this library, but perhaps if you're still experiencing the issue it's possible it is not being executed.

@geeknz I would suggest opening a new ticket if you're still experiencing issues, detailing what is happening in your code. The piece you have posted looks great.

**Comment by justingreerbbi** [comment]
Yup, I seen that. I don't want to hijack the thread but I don't think the second line example is working. I will continue to poke around and open a new ticket with a possible patch.

**Comment by geeknz** [comment]
@bshaffer Thank you. I discovered that the problem was actually in my UserCredentials implementation so it is working great now.

**Comment by hitswa** [comment]
I didn't get yet whare exactlt the problem is? Where do I need to change in code?

following cookbook from here
https://bshaffer.github.io/oauth2-server-php-docs/cookbook/

executing this command a instructed in document
curl -u testclient:testpass http://localhost/token.php -d 'grant_type=client_credentials'

getting following response
{"error":"unsupported_grant_type","error_description":"Grant type \"client_credentials\" not supported"}{"error":"unsupported_grant_type","error_description":"Grant type \"client_credentials\" not supported"}
