### ISSUE TITLE
Possible issue with UserCredentials  using PDO storage

### ISSUE THREAD

**Issue by gk1** [bshaffer/oauth2-server-php#380]
Trying to use PDO Storage with UserCredentials Grant type and it always returns:
{"error":"invalid_grant","error_description":"Invalid username and password combination"}

Using the in memory array from the UserCredentials example works perfectly, so seemingly there is something wrong with PDO, or i am missing a parameter.

I can see the query hitting my mysql database querying the oauth_users tables which has the user and password in it as specified on the command line.
curl -u testclient:testpass http://localhost/myoauth/token.php -d 'grant_type=password&username=user1&password=pass1'

server.php gist: https://gist.github.com/gk1/19d57d916dfbfe835ee7

**Comment by Colin81** [comment]
I know this issue was a long time ago but I just came across it now. I really think this page http://bshaffer.github.io/oauth2-server-php-docs/grant-types/user-credentials/
needs to say something about this to make it clear that pdo is hashing passwords before comparing.
