### ISSUE TITLE
Getting User Info upon Login

### ISSUE THREAD

**Issue by martinzaleski** [bshaffer/oauth2-server-php#381]
I need to get the userid when logging in, and I just can't find the way to do it.

I'm sending this info:
{
            "username":USERNAME,
            "password": PASSWORD,
            "grant_type" : "password",
        "client_id" : CLIENT

}
and I get the following response:
{
access_token: "23f32b51076912b193b648c0b54ddb518546fa38"
expires_in: 3600
token_type: "Bearer"
scope: null
refresh_token: "233086f639d78b77896b2f2a583072809c537910"
}

I just can't get the user info.

On the other hand, it would be nice as well to be able to, in random calls, return information related to the user making the call, basing on the bearer token without needing to have an ID posted by GET or POST.
i.e:
www.myapp.com/api/getcollections ---cool
www.myapp.com/api/getcollections/id ---not cool

Thank you!!

**Comment by theroadrunnershow** [comment]
https://developers.google.com/drive/web/credentials

**Comment by handokox8** [comment]
@bshaffer how about userinfo endpoint ? I'm looking for userinfo endpoint documentation. After implement openid with this lib, I got id_token. Then how handle this, so it can be used to access userinfo. Thanks.
