### ISSUE TITLE
"error":"invalid_request"

### ISSUE THREAD

**Issue by utpal4job** [bshaffer/oauth2-server-php#427]
Hello, I have downloaded your script and also implemented the code as said on "http://bshaffer.github.io/oauth2-server-php-docs/cookbook/" url. But try to run the script i get the below errors:

{"error":"invalid_request","error_description":"The request method must be POST when requesting an access token","error_uri":"http:\/\/tools.ietf.org\/html\/rfc6749#section-3.2"}

Please tell me how to solve the issue.

Regards,

**Comment by mfarhanahmad** [comment]
@bshaffer I am able to initiate the token successful and also token is validating correctly on my resource page. Just one thing that I want to know,

On expiring token How can I generate a new token with refresh token ?
