### ISSUE TITLE
"error":"invalid_client"

### ISSUE THREAD

**Issue by utpal4job** [bshaffer/oauth2-server-php#429]
Hello, When try to run "curl -u testclient:testpass http://localhost/token.php -d 'grant_type=client_credentials" command then below error is appearing.
{"error":"invalid_client","error_description":"Client credentials were not found in the headers or body"}

Can you please tell me why that error is appearing.

Regards,

**Comment by justingreerbbi** [comment]
OAuth2/request.php line 137 (PHP CGI)
