### ISSUE TITLE
Allow access_token in PUT request body

### ISSUE THREAD

**Issue by R11baka** [bshaffer/oauth2-server-php#436]
Plz allow access_token in request body.For post,all working good but,when i request PUT method.
then in  bearer.php file in 75 line ,return false 

```
#bearer.php
(bool)$request->request($this->config['token_param_name'])
```

and code 

```
#bearer.php
     if ($methodsUsed == 0) {
            $response->setStatusCode(401);

            return null;
        }

```

 and set error

**Comment by TomHAnderson** [comment]
:+1: to Authorization: Bearer header

**Comment by bshaffer** [comment]
I believe this is allowed if you use the [`Request`](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/Request.php#L202) class. It may not be allowed when using `HttpFoundation`
