### ISSUE TITLE
Grant type "password" not supported

### ISSUE THREAD

**Issue by almaruf** [bshaffer/oauth2-server-php#445]
When or If you are going to implement this grant_type

**Comment by arundevpv** [comment]
I saw the same error. And i also found ,where is the problem happen. I'am using Pdo as storage medium.
In Oauth2/Storage/Pdo.php Line 317,
**if (!$userInfo = $stmt->fetch(\PDO::FETCH_ASSOC)) { 
            return false;
   }**
**_Undefined variable: userInfo in /var/www/html/oauth2/src/OAuth2/Storage/Pdo.php on line 317_**
