### ISSUE TITLE
addGrantType() Error

### ISSUE THREAD

**Issue by almaruf** [bshaffer/oauth2-server-php#450]
$storage = new Api_Oauth2Storage( $params );
$server = new OAuth2\Server($storage, $config);

I get the error while trying this 
$server->addGrantType(new OAuth2\GrantType\ClientCredentials($storage));

Argument 1 passed to OAuth2\Server::addGrantType() must be an instance of OAuth2\GrantType\GrantTypeInterface, instance of OAuth2\GrantType\ClientCredentials give

But no error for this
$server->addGrantType(new OAuth2\GrantType\UserCredentials($storage));

Missing something obvious ?

**Comment by produktive** [comment]
@almaruf I am having the same problem and I am using the same OAuth2 client. How did you fix this problem?

**Comment by almaruf** [comment]
not sure its a great solution, but I changed the namespace used by the Oauth2 client, that works
