### ISSUE TITLE
refresh_tokens life time

### ISSUE THREAD

**Issue by nssilva** [bshaffer/oauth2-server-php#464]
Hello, sorry if this was asked allready but i did not see it.

I have a small implementation of OAuth2 php and i am using refresh tokens when access tokens expires, i am also using always_issue_new_refresh_token to true.

My question is: How can i make that the old one loses those 14 days? is there a way of expire as soon as a new one is generated?

Thanks.

P.S-> I whan to thanks the author for OAuth2, i also whant to ask if is possible to implement a small or not so small implementation of a OAuth2 provider as an example, i ask this because its a tricky part and hard one too.

**Comment by donearh** [comment]
the same situation need more detail information about what we need to do if refresh token expired

**Comment by bshaffer** [comment]
@donearh this issue is closed. If you have a similar problem, please open a [new issue](https://github.com/bshaffer/oauth2-server-php/issues/new) and provide us with as much detail as you can on how we can reproduce it.

Thank you!
