### ISSUE TITLE
How do I implement Memory Storage

### ISSUE THREAD

**Issue by sandinosaso** [bshaffer/oauth2-server-php#469]
I am using memory for users_credentials and access_token I am using grant_type 'password' I am succesfull validating user with memory saved user_credential and token the problem is when getting a new token it is not saved to memory again do not know how to implement this kind of funcionality

What I am doing is:

``` php
$tokens_in_memory = array('access_tokens'=>array(                                                       '42e13ba1c0e33036889617ee45c0d0ee7b28653f'=>array('access_token'=>'42e13ba1c0e33036889617ee45c0d0ee7b28653f',                                                                                                         'client_id'   => 'test_client',                                                                                                         'user_id'     => '_app_user',                                                                                                       'expires'     => strtotime('2014-10-05 22:45:48'))
                                                        )
                                 );

$tokenStorage = new OAuth2\Storage\Memory($tokens_in_memory);
...
...
$this->server->addStorage($tokenStorage, 'access_token');
```

This is done on my controller init method I think it is overwriting everytime so I am not able to generate new tokens in memory, the PDO solution works geat but doing some kind of apache benchmark it shows that is 100x slower than doing in memory, I will be checking many tokens per second so the fastest I can do it the better, it would be great to suppor MemCache as well I will investigate if I can do it and make a pull request.

I inspected code and see that TokenController calls:

``` php
function grantAccessToken(RequestInterface $request, ResponseInterface $response)
```

and it returns:

``` php
return $grantType->createAccessToken($this->accessToken, $clientId, $grantType->getUserId(), $requestedScope);
```

and at the end in te createAccessToken it calls:

``` php
 $this->tokenStorage->setAccessToken($token["access_token"], $client_id, $user_id, $this->config['access_lifetime'] ? time() + $this->config['access_lifetime'] : null, $scope);
```

In my case tokenStorage is memory but I do not see news token persisted, maybe you have a php server in memory running, or do you save to session or something 

I am doing an api using Yii is kind of easy integrate it with your library and it would be great to have it merged next releases of Yii if I make it work I will share code to make this library work with Yii .

Thank you, you all

**Comment by pjebs** [comment]
I was wondering what the progress was of this? It would definitely be a useful addition

**Comment by bshaffer** [comment]
I don't think @sandinosaso ever submitted a pull request... but feel free to submit one as well @pjebs

**Comment by sandinosaso** [comment]
I never did but I can if you let me, the code is really simple as bshaffer suggested I implemented passing a valid storage, so I am using PDO storage with a mysql database and usign Memcache to faster retrieve access tokens

<code>
<?php
namespace OAuth2\Storage;
use Memcache;

class MemCacheToken implements AccessTokenInterface
{
    protected $storage;
    protected $memcache;

    public function __construct(AccessTokenInterface $storage, $config=array())
    {
        $this->storage = $storage;

        $this->memcache = new Memcache;

        $host    = isset($config['host'])    ? $config['host']    : 'localhost';
        $port    = isset($config['port'])    ? $config['port']    : 11211;
        $timeout = isset($config['timeout']) ? $config['timeout'] : 1;

        $this->memcache->connect($host, $port, $timeout);
    }

    public function getAccessToken($access_token)
    {
        $cacheKey = 'storage-'.$access_token;           

        # Try and get from memory
        $accessToken = $this->memcache->get($cacheKey);

        # We have some data
        if(!empty($accessToken)) {
            return $accessToken;
        }

        $accessToken = $this->storage->getAccessToken('access_token');
        $this->memcache->set($cacheKey, $accessToken, 0, strtotime($accessToken['expires']));

        return $accessToken;
    }

    public function setAccessToken($oauth_token, $client_id, $user_id, $expires, $scope = null)
    {
        $cacheKey = 'storage-'.$oauth_token;           

        $this->storage->setAccessToken($oauth_token, $client_id, $user_id, $expires, $scope);
        $updatedAccessToken = $this->storage->getAccessToken($oauth_token);

        $result = $this->memcache->replace($cacheKey, $updatedAccessToken, 0, $expires);
        if( $result == false ) 
        { 
            $result = $this->memcache->set($cacheKey, $updatedAccessToken, 0, $expires);
        }

    }
}
</code>

For use it just do

<code>
		try {
			$pdotokenStorage = new OAuth2\Storage\Pdo(array('dsn' => $dsn, 'username' => $username, 'password' => $password));
		}catch(PDOException $e) {
			//Send email with error
			Yii::app()->EmailSenderComponent->send('Database Error', $e->getMessage());
                        //Log the error
			Yii::log('Database error :'.$e->getMessage(), 'error', 'application.ApiController.init');
			$this->_sendResponse(500, json_encode(array ('status'=> 500, 'message'=> 'Internal error contact the admin', 'code'=> 20003)), array('Content-type'   => 'application/json') );
		}
		// USING PDOMEMCACHE
		$tokenStorage = new OAuth2\Storage\MemCacheToken($pdotokenStorage);

</code>

You can also pass an array of parameter to choose wich MemCache server you want to connect
Like this $tokenStorage = new OAuth2\Storage\MemCacheToken($pdotokenStorage, array('host' =>'YOURHOST', 'port'=>YOUR_PORT_NUMBER));

**Comment by sandinosaso** [comment]
I created a pull request https://github.com/bshaffer/oauth2-server-php/pull/608
