### ISSUE TITLE
Invalid Credentials

### ISSUE THREAD

**Issue by sureshsharma** [bshaffer/oauth2-server-php#477]
I have gone through with your example http://bshaffer.github.io/oauth2-server-php-docs/cookbook/.

We are trying to implement the example you explained. But we are getting "error: "invalid_client"
error_description: "Client credentials were not found in the headers or body""

we are using grant_type : Client_credentials

we are getting response but i don't know what is the problem

I don't know where we are wrong. Could you please help me? Its really very important for me.

Resources used:

OS used: WIN7(32-BIT),8,8.1(64-BIT) 
Server package: Wampserver

**Comment by arundevpv** [comment]
I saw the same error. And i also found ,where is the problem happen. I'am using Pdo as storage medium.
In Oauth2/Storage/Pdo.php Line 317,
**if (!$userInfo = $stmt->fetch(\PDO::FETCH_ASSOC)) { 
            return false;
   }**
**_Undefined variable: userInfo in /var/www/html/oauth2/src/OAuth2/Storage/Pdo.php on line 317_**
I changed that code to,
**$userInfo = $stmt->fetch(\PDO::FETCH_ASSOC);**
Now it is working.
**_Note:_**In db store the password in encrypted format ,use sha1().
