### ISSUE TITLE
oauth2 group management

### ISSUE THREAD

**Issue by etcware** [bshaffer/oauth2-server-php#486]
Is possible to associate user to a group list and get group list by using token?
Thanks

**Comment by TomHAnderson** [comment]
This sounds like you have a group-list endpoint and you want to use an access_token to query it.  

Do you think it's more complicated than that?  Are you suggesting users use groups to define clients?

**Comment by bshaffer** [comment]
@etcware nothing like this happens out of the box with this library. You could easily implement the `OAuth2\Storage\UserInterface` and then associate that user with a group. But that is out of the scope of this library.
