### ISSUE TITLE
How to add a prefix to the tables

### ISSUE THREAD

**Issue by Deep21** [bshaffer/oauth2-server-php#495]
Hello everyone, 
I need your help, Actually I'am trying to integrate oauth2-server-php to my REST api and my db use table prefix. As I can see in Pdo.php file all the sql queries are hard coded.
 
Is there any proper way to add a prefix name to the tables ?

Thank you

**Comment by needcaffeine** [comment]
Hello @Deep21 -- take a look at https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/Storage/Pdo.php

You can pass in your own table names to that function, or extend it within your application.

**Comment by Deep21** [comment]
Thank you @needcaffeine
