### ISSUE TITLE
"The value must not be empty" error message when using DynamoDB storage.

### ISSUE THREAD

**Issue by djhunx** [bshaffer/oauth2-server-php#505]
I am using the DynamoDB as storage. When I try to get an access token with grant_type 'client_credentials' or 'password',  I get the "The value must not be empty" error message. I traced  the error down to the 'setAccessToken' function of DynamodDB 

bshaffer\oauth2-server-php\src\OAuth2\Storage\DynamoDB.php

```
 public function setAccessToken($access_token, $client_id, $user_id, $expires, $scope = null)
    {
        // convert expires to datestring
        $expires = date('Y-m-d H:i:s', $expires);

        $clientData = compact('access_token', 'client_id', 'user_id', 'expires', 'scope');
        $clientData = array_filter($clientData, function ($value) { return !is_null($value); });

        $result = $this->client->putItem(array(
            'TableName' =>  $this->config['access_token_table'],
            'Item' => $this->client->formatAttributes($clientData)
        ));

        return true;

    }

```

It seems DynamoDB bombs out when i try to save an item with an attribute having an empty value.

It works if i replace "!is_null($value)" with "!empty($value) line 174 

```
$clientData = array_filter($clientData, function ($value) { return !empty($value); });
```

Same error when refreshing tokens,

```
public function setRefreshToken($refresh_token, $client_id, $user_id, $expires, $scope = null)
    {
        // convert expires to datestring
        $expires = date('Y-m-d H:i:s', $expires);

        $clientData = compact('refresh_token', 'client_id', 'user_id', 'expires', 'scope');
        $clientData = array_filter($clientData, function ($value) { return !is_null($value); });

        $result = $this->client->putItem(array(
            'TableName' =>  $this->config['refresh_token_table'],
            'Item' => $this->client->formatAttributes($clientData)
        ));

        return true;
    }
```

Is there a better solution/workaround this?  Thanks.

**Comment by bshaffer** [comment]
I believe this would work, yes. It means any `false` value would be equivalent to `null`, but I don't think we ever have a distinction from a storage standpoint.

**Comment by bshaffer** [comment]
Would you like to submit a PR for this and include a test in [this directory](https://github.com/bshaffer/oauth2-server-php/tree/develop/test/OAuth2/Storage)?

**Comment by djhunx** [comment]
Hi, I find that an empty string ' ' is being passed to the  setAccessToken and setRefreshToken functions when there is no default scope in the oauth_scopes table in dynamodb. On second thought, do you think it's better to expect a null value when we don't intend to pass a scope into the function ?

When no scope is passed, the scope is taken from the getDefaultScope() function of the storage and it returns the empty string when there is none set in the database.
The function can be modified to return null instead like

bshaffer\oauth2-server-php\src\OAuth2\Storage\DynamoDB.php
```
public function getDefaultScope($client_id = null)
    {

        $result = $this->client->query(array(
            'TableName' => $this->config['scope_table'],
            'IndexName' => 'is_default-index',
            'Select' => 'ALL_ATTRIBUTES',
            'KeyConditions' => array(
                'is_default' => array(
                    'AttributeValueList' => array(array('S' => 'true')),
                    'ComparisonOperator' => 'EQ',
                ),
            )
        ));
        $defaultScope = array();
        if ($result->count() > 0) {
            $array = $result->toArray();
            foreach ($array["Items"] as $item) {
                $defaultScope[]  = $item['scope']['S'];
            }
            return empty($defaultScope) ? null : implode(' ', $defaultScope);           
        }

        return null;
    }
```

In line 414, change
```
return implode(' ', $defaultScope);
```
to
```
return empty($defaultScope) ? null : implode(' ', $defaultScope);
```

If you agree, could you also suggest how to write the test. The default scopes in the oauth_scopes table created on bootstrap have to be cleared to test for this use case.

**Comment by bshaffer** [comment]
I agree, as `null` is the return value we have defined in [the documentation](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/Storage/ScopeInterface.php#L36).

This is probably not worth an integration test. You should create a mock [`DynamoDBClient`](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/Storage/DynamoDB.php#L51) and pass it to the DynamoDB storage object, then define the client to return an empty string and test the storage object returns `null`.

The other fix for empty values does deserve an integration test.
