### ISSUE TITLE
Adopt semantic versioning

### ISSUE THREAD

**Issue by Maks3w** [bshaffer/oauth2-server-php#507]
I suggest this project adopt [Semantic Versioning guidelines](http://semver.org/) for release versions.

This make easy fast upgrade for fixes without deal with backward compatibility breaks like the recent #437

**Comment by bshaffer** [comment]
This is a good idea. I assume you were checked out to "1.*" or "~1.0"?

On Tuesday, January 27, 2015, Maks3w <notifications@github.com> wrote:

> I suggest this project adopt Semantic Versioning guidelines
> <http://semver.org/> for release versions.
>
> This make easy fast upgrade for fixes without deal with backward
> compatibility breaks like the recent #437
> <https://github.com/bshaffer/oauth2-server-php/pull/437>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bshaffer/oauth2-server-php/issues/507>.
>


-- 
Sincerely,
Brent Shaffer
@bshaffer <http://twitter.com/bshaffer>

**Comment by Maks3w** [comment]
The second one is the expected for semantic versioning for Composer (https://getcomposer.org/doc/01-basic-usage.md#package-versions)

`composer require bshaffer/oauth2-server-php`

will produce

```
{
   "bshaffer/oauth2-server-php": "~1.6"
}
```

**Comment by bshaffer** [comment]
Thank you for bringing this up... I've been using the Brent-Semantics versions, which follows the guidelines "create a minor version whenever there are sufficient changes to justify it, and it's ok to break BC as long as you document it".

I like your suggestion better, and will adopt it for now on!
