### ISSUE TITLE
Stable version?

### ISSUE THREAD

**Issue by s-andy** [bshaffer/oauth2-server-php#513]
I'm slightly confused:

* [The site](http://bshaffer.github.io/oauth2-server-php-docs/) links to 0.9 as the stable version.
* But then also refers 1.6 (and 1.6 is newer than 0.9)

What is the stable version? 1.6?

**Comment by bshaffer** [comment]
Those links refer to the PHP 5.2 versions of the library. 1.6 is the
current stable version.

On Friday, February 6, 2015, Andriy Lesyuk <notifications@github.com> wrote:

> I'm slightly confused:
>
>    - The site <http://bshaffer.github.io/oauth2-server-php-docs/> links
>    to 0.9 as the stable version.
>    - But then also refers 1.6 (and 1.6 is newer than 0.9) What is the
>    stable version? 1.6?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bshaffer/oauth2-server-php/issues/513>.
>


-- 
Sincerely,
Brent Shaffer
@bshaffer <http://twitter.com/bshaffer>
