### ISSUE TITLE
Empty response json specification

### ISSUE THREAD

**Issue by jimekevin** [bshaffer/oauth2-server-php#525]
Is there any specification for the json response type when no authentication information is included in the request? http://tools.ietf.org/html/rfc6750#section-3.1 specifies that _" [...] the resource server SHOULD NOT include an error code or other error information"_ but sending the response object of the oauth2 server results in `[]` with status code 401.

```
$globalRequest = Request::createFromGlobals();
if (!$oauth2Server->verifyResourceRequest($globalRequest, null)) {
    $response = $oauth2Server->getResponse();
    $response->send();
}
```

I'd either expect a blank response or an empty object `{}`. Using `JSON_FORCE_OBJECT` in `Response::getResponseBody` resolves this.

**Comment by bshaffer** [comment]
I believe we want no response. The `[]` (or even `{}`) is not desirable. Would you like to submit a PR to fix this?

**Comment by mehmedean** [comment]
Sending no access_token still results in  `[]`, is there any fix on this?

**Comment by mehmedean** [comment]
Thank you Brent, it now returns an empty response body.
