### ISSUE TITLE
User Credentials Grant without client_secret

### ISSUE THREAD

**Issue by clawish** [bshaffer/oauth2-server-php#528]
Hello guys,
first of all: **this library is pure gold!** Thank you also for the great documentation.

On http://bshaffer.github.io/oauth2-server-php-docs/grant-types/user-credentials/ it is said that 

> If your client is `public` (by default, this is true when no secret is associated with the client), you can omit the `client_secret` value in the request

Being a mobile application, my client is public. I want to add a client to the `oauth_clients` in my database for my app. However, when I try to omit the `client_secret`, by inserting `NULL`

    INSERT INTO oauth_clients (client_id, client_secret, redirect_uri) VALUES ("prepnet", NULL, "/ref");

I receive the error 

    Column 'client_secret' cannot be null.

How would I omit the `client_secret` for my public client?
If I just try to request a token without a `client_secret` via

    $ curl https://api.mysite.com/token -d 'grant_type=password&client_id=TestClient&username=bshaffer&password=brent123'

I receive the json from the server

    This client is invalid or must authenticate using a client secret

(While the client exists in the `oauth_clients` table, with the `client_id` of `TestClient` and some `client_secret`.)
Again:  How would I omit the `client_secret` for my public client?
Thank you for your help.

**Comment by bshaffer** [comment]
You could just submit an empty string for `client_secret` in the database, or allow the column to be `null` in your table configuration.

Where did you get the SQL to create your table?

**Comment by clawish** [comment]
Alright, very nice.
I got the SQL from [the cookbook](http://bshaffer.github.io/oauth2-server-php-docs/cookbook/).

**Comment by bshaffer** [comment]
yep... looks like we need to remove the `NOT NULL` from the `client_secret` column there.  Thanks for reporting this!

**Comment by mtangoo** [comment]
This was forgotten open.
To just add to this question, is submitting client_id over Authorization header (base64 encoded) a standard practice? I have seen a library doing that automatically. Am not sure if this server handles that automatically (I know it does very well if passed along username and password in password grant as an example)

**Comment by bshaffer** [comment]
Closing this, as it's now fixed.

@mtangoo This is not standard practice AFAIK.
