### ISSUE TITLE
Client credentials were not found in the headers or body

### ISSUE THREAD

**Issue by poisa** [bshaffer/oauth2-server-php#531]
Hi, I'm following the docs for https://github.com/zfcampus/zf-oauth2 and so far so good except that when it comes to testing the server I get this.
Any help will be greatly appreciated!

Using httpie:
```
POST /oauth HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: Basic dGVzdGNsaWVudDp0ZXN0cGFzcw==
Connection: keep-alive
Content-Length: 29
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Host: tsp.dev
User-Agent: HTTPie/0.9.2

grant_type=client_credentials

HTTP/1.1 400 invalid_client
Connection: close
Content-Type: application/problem+json
Date: Wed, 04 Mar 2015 04:51:11 GMT
Server: Apache
Transfer-Encoding: chunked
X-Powered-By: PHP/5.5.10

{
    "detail": "Client credentials were not found in the headers or body", 
    "status": 400, 
    "title": "invalid_client", 
    "type": "http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html"
}
```

Using curl:
```
curl -X POST -d 'grant_type=client_credentials&username=testclient&password=testpass' http://tsp.dev/oauth
* Adding handle: conn: 0x7fa713004000
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x7fa713004000) send_pipe: 1, recv_pipe: 0
* About to connect() to tsp.dev port 80 (#0)
*   Trying 127.0.0.1...
* Connected to tsp.dev (127.0.0.1) port 80 (#0)
> POST /oauth HTTP/1.1
> User-Agent: curl/7.30.0
> Host: tsp.dev
> Accept: */*
> Content-Length: 67
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 67 out of 67 bytes
< HTTP/1.1 400 invalid_client
< Date: Wed, 04 Mar 2015 04:55:29 GMT
* Server Apache is not blacklisted
< Server: Apache
< X-Powered-By: PHP/5.5.10
< Connection: close
< Transfer-Encoding: chunked
< Content-Type: application/problem+json
< 
* Closing connection 0
{"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"invalid_client","status":400,"detail":"Client credentials were not found in the headers or body"}
```

**Comment by TarasHots** [comment]
I guess you should use client_id and client_secret instead of username with password(which are reffered to user_credentials grant type). Try this:

`$ curl -u TestClient:TestSecret https://api.mysite.com/token -d 'grant_type=client_credentials'`

or 

`$ curl https://api.mysite.com/token -d 'grant_type=client_credentials&client_id=TestClient&client_secret=TestSecret'`

as mentioned in https://bshaffer.github.io/oauth2-server-php-docs/grant-types/client-credentials/

**Comment by poisa** [comment]
Gotcha. Thanks!

**Comment by marcelojlf23** [comment]
> I guess you should use client_id and client_secret instead of username with password(which are reffered to user_credentials grant type). Try this:
> 
> `$ curl -u TestClient:TestSecret https://api.mysite.com/token -d 'grant_type=client_credentials'`
> 
> or
> 
> `$ curl https://api.mysite.com/token -d 'grant_type=client_credentials&client_id=TestClient&client_secret=TestSecret'`
> 
> as mentioned in https://bshaffer.github.io/oauth2-server-php-docs/grant-types/client-credentials/

thank you very much after hours i found your answer that and solved my problem
