### ISSUE TITLE
Class PDO not found in OAuth2\Storage\Pdo on line 53

### ISSUE THREAD

**Issue by jonbest** [bshaffer/oauth2-server-php#532]
`Fatal error: Class 'PDO' not found in /path/to/docroot/vendor/bshaffer/oauth2-server-php/src/OAuth2/Storage/Pdo.php on line 53`

I've been working to resolve this a few different ways but am unable to do so thus far. I've installed via composer into CodeIgniter, as opposed to [bug 326](https://github.com/bshaffer/oauth2-server-php/issues/326). I am following the step-by-step walkthrough while adapting to CI. I've built the server.php file as a library and am at the token step. My library looks like this:

```php
<?php if(!defined('BASEPATH')) exit('No direct script access allowed');

class OAuthServer
{
	private $ci;
	private $server;
	private $storage;
	
	public function __construct()
	{
		$this->ci =& get_instance();
		
		$this->ci->load->database('api');
		$dsn = 'mysql:dbname='.$this->ci->db->database.';host='.$this->ci->db->hostname;
		$username = $this->ci->db->username;
		$password = $this->ci->db->password;
		
		if(ENVIRONMENT != 'production')
		{
			ini_set('display_errors', 1);
			error_reporting(E_ALL);
		}
		
		$this->storage = new OAuth2\Storage\Pdo(array(
			'dsn'		=> $dsn,
			'username'	=> $username,
			'password'	=> $password
		));
		
		$this->server = new OAuth2\Server($this->storage);
		$this->server->addGrantType(new OAuth2\GrantType\ClientCredentials($this->storage));
		$this->server->addGrantType(new OAuth2\GrantType\AuthorizationCode($this->storage));
	}
	
	public function handleTokenRequest($request, $response)
	{
		return $this->server->handleTokenRequest($request, $response);
	}
}
```
and my token controller so far...
```php
<?php if(!defined('BASEPATH')) exit('No direct script access allowed');

require_once APPPATH.'controllers/StandOutControllerUnsessioned.php';

class Token extends StandOutControllerUnsessioned
{
	public function __construct()
	{
		parent::__construct();
		
		$this->load->library('oauthserver');
	}
	
	public function index()
	{
		$this->oauthserver->handleTokenRequest(OAuth2\Request::createFromGlobals())->send();
	}
}
```

i can remove the storage component and receive exceptions from the library (`'Unable to build default grant types - You must supply an array of grant_types in the constructor'`) which leads me to believe the libraries are loaded correctly. Not to mention, the error received cites a line number in the PDO class itself. I'm assuming there's not an issue this major in the build, so any thoughts on what i'm doing wrong would be great!

thanks in advance!

**Comment by jonbest** [comment]
this issue is invalid. it turns out that my build of php within centos 6 had --disable-pdo configured for some reason. i rebuilt with pdo and this works fine.

**Comment by bshaffer** [comment]
wow, thank you for posting this here for others having the same issue

**Comment by JonDaniel** [comment]
I had a similar issue on Centos 7 on a standard amazon box install (had not previously connected php to mysql though mysql was on the box for another reasons).  The following sorted me out:

yum install php-pdo.x86_64
yum install php-ZendFramework-Db-Adapter-Pdo-Mysql.noarch
yum install php-mysql.x86_64
yum install php-ZendFramework-Db-Adapter-Mysqli.noarch
