### ISSUE TITLE
Not sure if this is a bug but seems to be redundant fields

### ISSUE THREAD

**Issue by pjebs** [bshaffer/oauth2-server-php#535]
In your sample database table you create the oauth_clients table like this:

CREATE TABLE oauth_clients (client_id VARCHAR(80) NOT NULL, client_secret VARCHAR(80) NOT NULL, redirect_uri VARCHAR(2000) NOT NULL, grant_types VARCHAR(80), scope VARCHAR(100), user_id VARCHAR(80), CONSTRAINT client_id_pk PRIMARY KEY (client_id));

ISSUES:

1. It appears as if grant_types can be empty and still work. (for client credentials and authorization code g.t)

2. Is scope field redundant???? It doesn't seem to do anything.

i.e. When you use authorization-code g.t., client redirects user specifying what scope(s) they want, and if user authorizes, the scope(s) seems to get registered in the oauth_access_tokens table. That is all that is required to know that a particular token has that particular scope(s).

What is the scope field for in the oauth_clients table?

3. What is user_id field for in oauth_clients table?

Once again, for authorization code g.t., it is registered with particular token.
Why is the user_id field required for oauth_clients table???

**Comment by bshaffer** [comment]
if `scopes` is populated, it means the client is limited to the possibility of just those scopes
if `grant_types` is null, it means the client can use any grant type
`user_id` is if you want to tie a set of client credentials to a specific user

**Comment by pjebs** [comment]
Could you explain the user_id again in a bit more detail.
Does it mean a specific user IS the client?

**Comment by bshaffer** [comment]
Aes, and if `user_id` is populated in the client table, then that same value will be populated in the `user_id` field of the `access_token` for any access token created with those client credentials.

**Comment by nsams** [comment]
Does `scope` also limit the possible scopes when suing client credentials?
