### ISSUE TITLE
Call to a member function checkClientCredentials

### ISSUE THREAD

**Issue by duuushtin** [bshaffer/oauth2-server-php#538]
I've been following the step by step instruction in the documentation.I have autoloaded everything properly but when I try to execute this command curl -u testclient:testpass http://dustin.com/admin/Oauth2/token -d grant_type=client_credentials I am getting this error.
 <b>Fatal error</b>:  Call to a member function checkClientCredentials() on a non
-object in <b>C:\xampp\htdocs\galaxy\vendor\oauth2-server\src\OAuth2\ClientAsser
tionType\HttpBasic.php</b> on line <b>62</b><br />

**Comment by duuushtin** [comment]
Please help..:D

**Comment by pjebs** [comment]
You'll need to provide more details including your code.

**Comment by duuushtin** [comment]
I tested it in Codeigniter. Here is my controller.

<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
class Oauth2 extends AKTK_Controller{
	
	private $dsn      = 'mysql:dbname=oauth2_db;host=localhost';
	private $username = 'root';
	private $password = '';
	private $storage  = '';
	private $server   = '';
	
	public function __construct()
	{
		parent::__construct();
		// $dsn is the Data Source Name for your database, for exmaple "mysql:dbname=my_oauth2_db;host=localhost"
		$this->storage = new OAuth2\Storage\Pdo(array('dsn' => $this->dsn, 'username' => $this->username, 'password' => $this->password));
		
		// Pass a storage object or array of storage objects to the OAuth2 server class
		$this->server = new OAuth2\Server($this->storage);
		
		// Add the "Client Credentials" grant type (it is the simplest of the grant types)
		$this->server->addGrantType(new OAuth2\GrantType\ClientCredentials($storage));
		
		// Add the "Authorization Code" grant type (this is where the oauth magic happens)
		$this->server->addGrantType(new OAuth2\GrantType\AuthorizationCode($storage));
		
	}
	public function token()
	{
		// error reporting (this is a demo, after all!)
		ini_set('display_errors',1);error_reporting(E_ALL);
		// Handle a request for an OAuth2.0 Access Token and send the response to the client
		$this->server->handleTokenRequest(OAuth2\Request::createFromGlobals())->send();
	}
	
	
}

**Comment by pjebs** [comment]
You seem to be missing this line:

OAuth2\Autoloader::register();

**Comment by duuushtin** [comment]
yes I installed it using composer. I also have autoloaded it in the index.php.

// Path to the vendor folder for Composer
define('VENDORPATH', FCPATH.'vendor\\');
/*
 * --------------------------------------------------------------------
 * LOAD THE BOOTSTRAP FILE
 * --------------------------------------------------------------------
 *
 * And away we go...
 *
 */
require_once VENDORPATH.'oauth2-server\src\OAuth2\Autoloader.php';
OAuth2\Autoloader::register();
require_once BASEPATH.'core/CodeIgniter.php';

/* End of file index.php */
/* Location: ./index.php */

Weird thing is that the authorization part of the tutorial works. But everytime i run that particular curl command I receive an error.

**Comment by bshaffer** [comment]
Kooks like your `$storage` object is empty, but that should be impossible due to the requred constructor argument [here](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/ClientAssertionType/HttpBasic.php#L62).

Maybe it's something to do with your PHP version, that the typehints are being enforced. But you are setting `$this->storage` on one line, and then you are passing in just `$storage` in the proceeding lines... this would be null, and could possibly cause this error.

**Comment by duuushtin** [comment]
Thanks for this. Yes, I should have set it to $this->storage instead of $storage. The error has been fixed.:D
