### ISSUE TITLE
error in response when using invalid scope.

### ISSUE THREAD

**Issue by pjebs** [bshaffer/oauth2-server-php#541]
If you have a populated oauth_scopes table, and you make a response to:

/authorize?response_type=code&client_id=testclient&state=xyz&scope=zzz

with a scope that is not in the table, then the $bridgedResponse after running validateAuthorizeRequest is blank and invalid.

**Comment by pjebs** [comment]
i.e. no error or error_description in json response. the response is just empty

**Comment by bshaffer** [comment]
Check the status code, it's probably `400`

**Comment by pjebs** [comment]
No.
I'm just var_dumping $bridgedResponse and its contents are empty.

**Comment by pjebs** [comment]
I found out this error occurs:
1) Always when no state is provided regardless of scope
2) When state is provided and scope is invalid (not in oauth_scopes table).

How can I fix this?

**Comment by bshaffer** [comment]
Can you post your code? We have tests surrounding both of those cases, and the result is not an empty response.

It most likely has either to do with your integration, or with the bridge request/response classes.

**Comment by pjebs** [comment]
No bug - I didn't realise that sometimes $bridgeresponse is a redirect and othertimes it is not. When it is not, getContents() contains the error information. When it is a redirect, getContents is empty but you have to check location header.

Also this confused me a bit too:

http://bshaffer.github.io/oauth2-server-php-docs/controllers/authorize/

Receives a request object, returns false if the incoming request is not a valid Authorize Request. If the request is valid, returns an array of retrieved client details together with input. Applications should call this before displaying a login or authorization form to the user

It seems to always return a bool. Never an "array of client details".

**Comment by pjebs** [comment]
Safe to close.
