### ISSUE TITLE
Namespace collision with 'access_token'

### ISSUE THREAD

**Issue by ckmaresca** [bshaffer/oauth2-server-php#545]
We're getting some odd errors like this:
```
Type: ErrorException
Code: 8
Message: Array to string conversion
File: /vendor/bshaffer/oauth2-server-php/src/OAuth2/Storage/Pdo.php
Line: 124
```
I've traced it back to this line of code:
```
$token = $stmt->execute(compact('access_token'));
```
Reading the docs for `compact` suggests that it searches the 'current symbol table', which would be (I guess) all symbols globally (there is no note of any scope restrictions).

Because we are also auth'ing using oauth2 against 3rd party APIs, we have other strings labeled `access_token` in a 'parent' scope, and there seems to be a namespace collision here because of the use of `compact` rather than a more scope-restrictive function.  I'm guessing (this is rather hard to actually debug without modifying the oauth2-server code) that `compact` is returning an array with multiple values for `access_token` and `execute` is failing as it expects a string....

I'm not entirely sure I'm reading this correctly, so I'm curious if this is a correct understanding.  

If so, what can we do to solve it?   I suspect the answer is better scoping, but with inheritance, this is perhaps easier said than done.... 

[sidenote] I actually think that the overlapping string comes from a $_SESSION var as we use that as a temporary store for 3rd party tokens while processing a 3rd party oauth2 stream e.g. $_SESSION['3rdpartyapiname']['access_token'], which is obviously global in scope....

**Comment by ckmaresca** [comment]
Manged to isolate the namespace problems but using `compact` in a security context is probably not the wisest idea....

**Comment by bshaffer** [comment]
@ckmaresca can you elaborate on why `compact` is a security concern?

If you are using `register_globals`, then *that* is the security concern. Even so, the scope of the variables would remain local, and will not be affected.

**Comment by ckmaresca** [comment]
It turnout to be a conflict with two 'access_token' fields (I think, the problem went away when we changed how we were caching 3rd party tokens - I stopped looking after that).

Nothing to do with register_globals, but some vars are global by default, $_SESSION being the most obvious one.   

`compact` is a problem in an environment like ours where we are both an oauth server & multiple oauth clients at the same time.  Usually scope takes care of any issues (so does `compact` scope restrictions...), but there are some things (like $_SESSION) that you can't avoid because of the stateless nature of web clients.    Also, 3rd party `access_tokens` are returned in `get` strings, so there is a potential for confusion, particularly as local auth handled by your code gets lost in the transaction and we have to re-inject it into the request....

It's a useful shortcut, but I'd rather see a more explicit `access_token` identification than what is effectively a `grep` of the current namespace....  This is particularly true because your code looks for the token in certain super-globals ($_SESSION & $_GET + request headers) and adds the found token to a locally scoped array (which is then picked up by `compact`).   The chance for confusion is pretty high...

**Comment by bshaffer** [comment]
I am still not quite clear how to solve this. Could you elaborate on this by providing an example of how my library could make this less confusing?

**Comment by ckmaresca** [comment]
As I was trying to figure out what was going on, I noticed that you are creating a locally scoped set of values from super globals with this call https://github.com/bshaffer/oauth2-server-php/blob/6811d3d158be04a8b5539e9484d7465a91fcedb0/src/OAuth2/Request.php#L192 

From this new locally scoped set of variables you are getting the `access_token` by using `compact`, AFAIK (I haven't full traced things).  Effectively, you're searching for `access_token` in a sub-set of the global namespace by doing this, which can cause issues if a URL being submitted has an `access_token` in the `GET` string (as part of an `auth_redirect` for Facebook API access, for example) and is also supposed to be authenticated using either `$_SESSION` or `Authentication` in the HTTP header.

One way to resolve this is to more explicitly pass `access_token` from the allowed methods (`header`, `get`, `$_SESSION`) defined in the Oauth2 protocol (which you are loosely doing kinda) - maybe configuring a hierarchy so that `header` & `$_SESSION` are trusted first over `get`.  Maybe a test to see where the value is coming from after finding it using `compact`?  I don't know.....

That said, I think that this software is by far the best Oauth2 server for PHP.  We've used every single one, and yours is the one that consistently does what we want in the way we expect.   This is really just a potential problem I noticed as I was trying to debug our particular issue...

**Comment by bshaffer** [comment]
No problem! If there's some way we can correct this confusion, I'm happy to do it. Let's get to the bottom of this!

So, the hierarchy you are suggesting takes place in the [TokenType\Bearer](https://github.com/bshaffer/oauth2-server-php/blob/6811d3d158be04a8b5539e9484d7465a91fcedb0/src/OAuth2/TokenType/Bearer.php#L33) class. You will see the `Authorization` header is checked first, followed by the `request`, followed by the `query`. This is the precedence defined in the spec (*HTTP Header > POST > GET*). 

I do not believe `$_SESSION` is ever supposed to carry the `access_token` parameter. If I am wrong, please let me know (using the specification). So this is implemented correctly, to the best of my knowledge.

**Comment by bshaffer** [comment]
You will also notice in this class we do additional checking, to ensure the `access_token` isn't provided in more than one place ([here](https://github.com/bshaffer/oauth2-server-php/blob/6811d3d158be04a8b5539e9484d7465a91fcedb0/src/OAuth2/TokenType/Bearer.php#L73)), that the header is not malformed ([here](https://github.com/bshaffer/oauth2-server-php/blob/6811d3d158be04a8b5539e9484d7465a91fcedb0/src/OAuth2/TokenType/Bearer.php#L95)), that the request method is correct when the access token is in the post body ([here](https://github.com/bshaffer/oauth2-server-php/blob/6811d3d158be04a8b5539e9484d7465a91fcedb0/src/OAuth2/TokenType/Bearer.php#L106)) and that the content type is correct ([here](https://github.com/bshaffer/oauth2-server-php/blob/6811d3d158be04a8b5539e9484d7465a91fcedb0/src/OAuth2/TokenType/Bearer.php#L119))

**Comment by ckmaresca** [comment]
Could be - all I know is that `compact` wound up picking up more than one variable.  After the problem went away, I stopped investigating & closed the issue.  What I wrote above is what I reconstructed from memory - it could be right, wrong or something inbetween.  

FWIW - the way we solved it is by extracting the correct token from `$_SESSION` (where we store it specifically because all other references get lost in when you get a redirect from a 3rd party API [note: we also store it in `state` just in case...]) then 'artificially' injecting it into the current session as a 'fake' header (e.g. programmatically generated by the server, not submitted by the client).  We then call your code to Oauth2 the current client.

HTH figure out a better solution, but I don't have much more time to spend on this, too busy writing a json2json ETL tool.... ;-)

That solved it, and as much as I'd like to spend more time looking at this and figuring out a better way, this works for us (even if it is a hack).   It still doesn't solve the fundamental problem of potential namespace collisions, however.

**Comment by bshaffer** [comment]
hmm... I am definitely confused here. You should definitely not put an access token in the `state` parameter. This is a huge security concern. If an attacker can get between your user and your application, they would essentially have the user's credentials.

Also, you shouldn't need to store an access token in the session when you redirect... the redirect is performed in order to obtain an access token. If you already have one, why is the user being redirected? The access token should be generated and returned by the auth server, without the need to maintain user state.

**Comment by ckmaresca** [comment]
LOL, that's really funny - you actually assumed that it was in `state` unencrypted?  How cute.  

Anyway - you are confused.  I'm not talking about a stand-alone [bshaffer] Oauth2 server, but rather (if you read my posts again) a situation where the backend server is acting as both Oath2 server & client. 

[Long explanation]

If you auth with a 3rd party (say Facebook), they generate an Oauth2 redirect which comes back to the backend server via a web client.  It looks exactly the same as a redirect coming from your (bshaffer) Oauth2 server, complete with a `access_token` and there is ZERO state information about who it belongs to because http is stateless - remember this is on the backend which is acting as both Oauth2 server (bshaffer code) & Oauth2 client (say Guzzle for simplicity sake), where the user is using a (stateless) web client.

Before the Facebook authentication token can be accepted & saved for a specific given web client, we need to identify & authorize that web client (using an Oauth2 bearer token generated by [bshaffer]).  But, remember, we lost all context & state information in the transactions that generated the redirect FROM Facebook....   The only way to know who the client is is by somehow retrieving the [bshaffer] `access_token`, all while leaving the Facebook `access_token` (which we need to save) intact.

We do this by looking it up in `$_SESSION` (server side) which is tied to a web client cookie.   Because there is an off-chance that the cookie might be corrupted or deleted, we also have the [bshaffer] `access_token` passed as part of an encrypted string using the oauth2 `state` variable.  Which is convenient as some APIs use `state` as a `nonce` and require a pseudo random variable, plus we can use it to double check the legitimacy of the request in case someone's cookies got hijacked along the way....

After we retrieve the [bshaffer] `access_token`, we then inject it into the web client's request vars, typically as a `header`.   Then we can pass the request to the [bshaffer] Oauth2 server for validation.

This all works fine in theory, assuming that all 3rd party APIs send their `access_tokens` via `GET` and we inject our [bshaffer] `access_token` via a header.  But some APIs (like Fitbit) want to pass `access_token` via headers so they won't show up in logs....   Right now it's not an issue, but it soon will be as Fitbit switches from Oauth1 to Oauth2.   Yes, it's non-standard, no they won't care, yes it happens all the time - people regularly ignore standards when they don't suite their needs/philosophy/religion/dog/etc.

Because the current [bshaffer] code is grabbing ALL `access_tokens` variables across all the different methods available, it did, at one point, cause a namespace collision _in_our_situation_.  We've managed to resolve it for now, but I have a feeling it will be more of a problem in the future.

**Comment by phindmarsh** [comment]
> LOL, that's really funny - you actually assumed that it was in state unencrypted? How cute.

You would be surprised how many people do stupid stuff with this library, it's better to err on the side of stupidity then assume otherwise unfortunately.

**Comment by ckmaresca** [comment]
Well, I used to be on a red team many years ago, so I know just how stupid people can be.....

**Comment by ckmaresca** [comment]
[changed title to actually reflect what we are discussing]

**Comment by bshaffer** [comment]
Thanks @ckmaresca for taking the time to write such a thorough explanation. As the library is following the specification, and provides opportunities for subclassing in order to deal with the problem above, I am closing this issue.
