### ISSUE TITLE
Fix comment in docs

### ISSUE THREAD

**Issue by brabeji** [bshaffer/oauth2-server-php#546]
In step-by-step tutorial section "Create a Resource Controller" code there is a following comment

`// Handle a request for an OAuth2.0 Access Token and send the response to the client`

that is IMO a copy-paste typo.

**Comment by bshaffer** [comment]
good catch! Fixed in https://github.com/bshaffer/oauth2-server-php-docs/commit/2a6091e7c0c5dbf04207332e91b2b0e993da900b
