### ISSUE TITLE
Invalid Request -- State Parameter Is Required (Google Playground)

### ISSUE THREAD

**Issue by shanejeffery54** [bshaffer/oauth2-server-php#548]
I have found a lot of help with this error, but none that is specific to this library or PHP in general.

	HTTP/1.1 302 Found
	Location: https://ch-bacon1.viedu.org/authorize.php?scope=basic&redirect_uri=https%3A%2F%2Fdevelopers.google.com%2Foauthplayground&response_type=code&client_id=testclient&access_type=offline
	GET /oauthplayground/?error=invalid_request&error_description=The+state+parameter+is+required HTTP/1.1
	Host: developers.google.com

Any ideas?  I get this error when I use the 'basic' scope and all of the details outlined in your walkthroughs and hit the Authorize APIs button.

**Comment by bshaffer** [comment]
Yes, you must incorporate the `state` parameter in the request. Read more [here](http://www.thread-safe.com/2014/05/the-correct-use-of-state-parameter-in.html), but essentially it means you must supply `&state=xyz` in the query string, where `xyz` is some encoded session identifier for your user. This way a session cannot be hijacked. But the session identifier should not be useful, in case it is compromised, so it should be (ideally) something salted and hashed:

```
$state = sha1(sessionid() . 'some-salt');
```

Then you can verify the state against your session id when the authorization server passes it back.

**Comment by AlbinoDrought** [comment]
With the Google OAuth 2.0 Playground specifically, appending `?state=xyz` to the entered Authorization endpoint worked perfectly for testing
