### ISSUE TITLE
after hitting login button it redirect to blank page.

### ISSUE THREAD

**Issue by rikina-pip** [bshaffer/oauth2-server-php#551]
Hi

I am using this plugin in my symfony 2 app. I followed all instrutions but after hitting login button it redirec to blank page.
can you please help me out.

Thanks in advance
Rikin

**Comment by bshaffer** [comment]
Rikin,
That is certainly not enough information for us to help you out. I suggest looking at your error logs and turning the debug mode on in symfony. Ask on IRC (#symfony) or find someone with more experience to help you solve your issue.
