### ISSUE TITLE
How to save support scope to check in redis

### ISSUE THREAD

**Issue by andree9911** [bshaffer/oauth2-server-php#553]
I want to define some support scope save in redis , how do it?

**Comment by bshaffer** [comment]
If you are looking to define a scope (say `somescope`), then just use the Redis function [`setScope`](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/Storage/Redis.php#L251) to do so

```php
$redis->setScope('somescope');
```
