### ISSUE TITLE
Resource request without access_token

### ISSUE THREAD

**Issue by davex69** [bshaffer/oauth2-server-php#560]
Hi,

Seems like I've found potential bug, when client make resource request with wrong `access_token` library validate it as https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/Controller/ResourceController.php#L82

But when client make request without `access_token` `$responce->send()` return only 401 code of header and empty array. I think should validate this type of error.

**Comment by bshaffer** [comment]
this is working as designed, the [TokenType](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/TokenType/Bearer.php#L86) is a `401` and no other information, as specified in the OAuth2 specification:

>  If the request lacks any authentication information (e.g., the client
   was unaware that authentication is necessary or attempted using an
   unsupported authentication method), the resource server SHOULD NOT
   include an error code or other error information.
