### ISSUE TITLE
Ignoring config key "issuer" when creating default JWT response type

### ISSUE THREAD

**Issue by glennschmidt** [bshaffer/oauth2-server-php#562]
In `Server::createDefaultJwtAccessTokenResponseType()`, need to add `issuer` to the list of config keys that are passed across to the `JwtAccessToken` constructor.

Currently only `store_encrypted_token_string` gets passed.

**Comment by bshaffer** [comment]
This is a good catch! We should definitely pass `issuer` to the `JwtAccessToken` class.

Would you like to submit a Pull Request to fix this?
