### ISSUE TITLE
Consider switching to firebase/php-jwt

### ISSUE THREAD

**Issue by F21** [bshaffer/oauth2-server-php#579]
When I wrote the code for JWT bearer tokens 2 years ago, there weren't many php jwt libraries around. The implementation of JWT used here was essentially my [F21/JWT](https://github.com/F21/jwt) library copied in.

Recently, it has been brought to my attention that the library suffers from a vulnerability if the same key is used for asymmetric and symmetric signing (which has since been patched). It's good to see that the issue has also been fixed here.

Having said that, I propose that we switch to [firebase/php-jwt](https://github.com/firebase/php-jwt), because they have implemented a lot of features and fixes and is the de-facto and most up-to-date jwt library for PHP.

**Comment by freezy-sk** [comment]
:+1:

**Comment by bshaffer** [comment]
totally agree with this one. @F21 would you like to set up a PR for this? I would like to include the firebase library under `suggest` and not `require` in composer, and throw an exception if it hasn't been installed.

**Comment by F21** [comment]
@bshaffer I just got a chance to look at the code and would love to get your perspective on some things.

In the JWT bearer grant type, response type, storage and OpenID response type, the EncryptionInterface is marked as optional in the constructor and if not passed in, the constructor instantiates an instance of JWT.

This seems a bit odd to me. If certain things require the JWT component, I think it's best to explicitly require the JWT component to be injected via the constructor.

Anyway, my proposal looks like this (this will be a major BC break):

- Remove `EncryptionInterface` and `JWT` encryption class.

- Where constructors require an argument of the `EncryptionInterface` type replace it with the `JWT class from `firebase/php-jwt`. We won't be coding to an interface, but this is acceptable IMO as we are not planning to have many implementations of a JWT interface anyway.

- The above will require a reshuffling of constructor arguments as we will be replacing all instances of `EncryptionInterface $encryptionUtil = null` with `JWT $jwt`.

- Add `firebase/php-jwt` as `suggest` in `composer.json`.

- No need to throw an exception if JWT is not installed, because we are making it mandatory to inject the JWT library into classes that require it.

Let me know what you think! There's going to be some major BC breaks, but I feel it is pretty worth it.

**Comment by Oxmoze** [comment]
Hi all,

As @bshaffer wrote, the firebase should not be defined as an hard dependency. There are other PHP libraries that provides great features and that can be used by the project. See [this library for example](https://github.com/Spomky-Labs/jose-service).

IMHO, you should not remove interfaces, but you should create "bridges" to use firebase or spomky-labs/jose or any other library (maybe in another repositories).

**Comment by F21** [comment]
@Oxmoze Good call!

I have converted the JWT class into a small bridge to use `firebase/php-jwt` in PR #582.
