### ISSUE TITLE
Multiple redirect URIs for clients

### ISSUE THREAD

**Issue by suj87** [bshaffer/oauth2-server-php#590]
Is it possible to have more than one redirect URI for clients, comma or space separated? If not would overriding the `validateAuthorizeRequest` function in the `AuthorizeController` be a clean solution?

**Comment by phindmarsh** [comment]
Space separated has worked for me in the past. 






On Fri, May 15, 2015 at 2:11 PM -0700, "suj87" <notifications@github.com> wrote:












Is it possible to have more than one redirect URI for clients, comma or space separated? If not would overriding the validateAuthorizeRequest function in the AuthorizeController be a clean solution?

**Comment by bshaffer** [comment]
We don't currently support multiple redirect URIs, but it would be a great enhancement.

Yes, `validateAuthorizeRequest` would be the way to go.

**Comment by bshaffer** [comment]
I take that back, @phindmarsh is correct, we support a space-separated list.  See the function [`validateRedirectUri`](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/Controller/AuthorizeController.php#L330)

**Comment by suj87** [comment]
Thanks for the update and confirmation guys! :-) :+1:
