### ISSUE TITLE
JwtAccessToken and 'jti' key in token data

### ISSUE THREAD

**Issue by basz** [bshaffer/oauth2-server-php#591]
Silly question perhaps, but why doesn't the JwtAccessToken ResponseType support the 'jti' key?

https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/ResponseType/JwtAccessToken.php#L64

As the Bearer does
https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/GrantType/JwtBearer.php#L107

**Comment by bshaffer** [comment]
Hmm, we should rename "id" to "jti". This was just done in oversight, I
believe.

**Comment by bshaffer** [comment]
We should add "jti" to `v1.x`, and remove "id" in `v2.x`

**Comment by bshaffer** [comment]
@basz please see #594 and verify this will satisfy your problem?

**Comment by basz** [comment]
@bshaffer all good - thanks!
