### ISSUE TITLE
Getting Users from 'user_table'

### ISSUE THREAD

**Issue by davigun** [bshaffer/oauth2-server-php#592]
// create some users in memory
$users = array('bshaffer' => array('password' => 'brent123', 'first_name' => 'Brent', 'last_name' => 'Shaffer'));

// create a storage object
$storage = new OAuth2\Storage\Memory(array('user_credentials' => $users));

// create the grant type
$grantType = new OAuth2\GrantType\UserCredentials($storage);

// add the grant type to your OAuth server
$server->addGrantType($grantType);

is there any way i could get users from the oauth_users table and not from dummy database like above?

Thank you before, anything else is working perfeclty.. :)

**Comment by bshaffer** [comment]
It depends on the type of storage you are using, and what you are looking for. The `UserCredentialsInterface` contains the method [`getUserDetails`](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/Storage/UserCredentialsInterface.php#L51), which takes a username as the argument, and returns an associative array of details about the user.

If you're looking for something more specific, I suggest dropping to the Query Language used by your storage engine.

**Comment by davigun** [comment]
Did you mean droping Query language to replace $users data from above??
okay then i will try. Thank you before

**Comment by bshaffer** [comment]
Hmm, rereading this, I think all you need to do is use the PDO storage
class instead of the Memory storage class

**Comment by davigun** [comment]
yeah, i already used the PDO (basic config where this PDO connect to DB) instead of using Memory, but it returns invalid pass and username combination, i think somehow it reads my dsn name username pass instead of reading from user_table.... So now i'm desperately confuse how can i retrieve data from user_table..

**Comment by bshaffer** [comment]
Sounds like the invalid pass/username error is concerning your PDO
credentials and not an oauth user's credentials. Can you paste the error
here?

**Comment by davigun** [comment]
![image](https://cloud.githubusercontent.com/assets/11326153/7803884/5b8848e2-0384-11e5-95ac-66b0f869111c.png)

that's the error prompt. and this is from the server.php

![image](https://cloud.githubusercontent.com/assets/11326153/7803894/899dcebe-0384-11e5-8b86-057abfcfe0fb.png)

storage changed from  >

![image](https://cloud.githubusercontent.com/assets/11326153/7803901/a98892cc-0384-11e5-8421-0a33719851f5.png)

**Comment by bshaffer** [comment]
Aha, I imagine the problem is that you are entering a plaintext password in the database, when it should actually be a `sha1`. You should use the [`addUser`](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/Storage/Pdo.php#L321) method in the PDO storage class.

**Comment by davigun** [comment]
ohh yeah mate, i got it wrong entering unencrypted password into database, my bad. Did you mean i have to change method setUser in Pdo class into addUser method? Because the link from your previous post is refering to setUser method in PDO (sorry got little confuse where the addUser is)

**Comment by bshaffer** [comment]
Haha no, use "setUser". It was just after midnight and I was tired.

**Comment by davigun** [comment]
Okay, got it, but i have to add public function setUser($username, $password, $firstName = null, $lastName = null); in the UserCredentialInterface class, so that this method can work properly. Thanks mate for your help, and sorry to disturb your night :)

**Comment by bshaffer** [comment]
You should be able to use the setUser method that I linked to as part of
the PDO storage class!

**Comment by davigun** [comment]
yeah i did use it, but in UserCreden interface class i have to decrale the function to call setUser method in the PDO storage class, either way it will return the same error as i mention in previous comment

**Comment by bshaffer** [comment]
No, if you add users using setUser, you will not get the error. The
password is being encrypted in setUser because it is insecure to store
these in plaintext.

**Comment by davigun** [comment]
yeah, im using setUser from now on, and have to change the password stored in database to SHA1 type, so that this password can correctly match when being searched by the method, and have to call the setUser function in UserCredenInterface class to make this works

![image](https://cloud.githubusercontent.com/assets/11326153/7851319/c601c8ee-0517-11e5-9bb8-edebbc83ef53.png)


like the above
