### ISSUE TITLE
Changing users table

### ISSUE THREAD

**Issue by JerryBels** [bshaffer/oauth2-server-php#600]
I successfully get a token using user credentials. But I would like to use another table, not oauth_users, to get the users and verify them.

I have read this :

    Note: User storage is highly customized for each application, so it is highly recommended you implement your own storage using OAuth2\Storage\UserCredentialsInterface

But since I'm not sure what it means (noob time !), I continued searching, to find that I can replace the table using an array of options like that :

    $storage = new OAuth2\Storage\Pdo(array('dsn' => $dsn, 'username' => $username, 'password' => $password), array('user_table' => 'users'));

The issue is that in the storage/Pdo script it uses the fields from the oauth_users table, not from the one I just entered, of course. For example, it uses username, where in my users table I use email, that is the default of Laravel.

What would be the solution about that ? Adding the username field in email table and maintain both ? Register users in both users table and oauth_users table ? Eat a cookie ?

Thanks for any help :)

**Comment by phindmarsh** [comment]
You should look at implementing your own storage class that implements the `UserCredentialsInterface`. This will allow you to write all your own logic for getting user credentials and sideload it into the server instance. 

IIRC you are using Laravel, so when you make your singleton you'll do something like this:

```php
App::singleton('oauth2', function() {
    
    //create your server as you are now, this is just from the cookbook example.
    $storage = new OAuth2\Storage\Pdo(App::make('db')->getPdo());
    $server = new OAuth2\Server($storage);
    
    // here you are setting your custom user storage class as the object to use to fetch
    // credentials for your server.
    $myUserStorage = new MyCustomUserStorageClass();
    $server->addStorage($myUserStorage, 'user_credentials');

    // whatever other server code you have...    

    return $server;
});
```

Implementing the UserCredentials interface in you own class should be straightfoward enough, you'll just need to make sure you return the right stuff. If you are looking for hints check out the existing Pdo Storage classes for ideas.

**Comment by JerryBels** [comment]
@phindmarsh thanks, that helps ! 

So I would do 

    class MyCustomUserStorageClass implements OAuth2\Storage\UserCredentialsInterface {
        public function checkUserCredentials($username, $password) { //stuff }
        public function getUserDetails($username) { //stuff }
    }

and return whatever is expected as can be seen in the comments here https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/Storage/UserCredentialsInterface.php and then when I'm checking access tokens with User Credentials grant

    $server->handleTokenRequest(OAuth2\Request::createFromGlobals())->send();

 it would use my own checkUserCredentials and getUserDetails in place of the default ones ?

Also, in this : 

    $grantType = new OAuth2\GrantType\UserCredentials($storage);

Do I have to use $myUserStorage instead ?

Thanks again !

**Comment by phindmarsh** [comment]
Yep thats right. You should *not* need to modify the library code itself, if you find you are changing internal classes etc you are probably not on the right track.

Also correct on passing the custom storage to the grant types as required. This lib is very extensible that way, almost all of it can be overloaded with custom code and configured when you build the server. 

Good work :+1:

**Comment by JerryBels** [comment]
Thanks :)

**Comment by sajumani** [comment]
hi,

am also trying to integrate User credential grant type... Will you people give clear doc...?
