### ISSUE TITLE
How to use Auth only but no resource server?

### ISSUE THREAD

**Issue by muhaha03** [bshaffer/oauth2-server-php#619]
I don't need to access resource server and just got to use the authentication method.
How to do that with this lib?

**Comment by bshaffer** [comment]
@muhaha03 you just need to configure an AuthorizeController then. But if you configure a Server object and then just call the `AuthorizeController` methods (i.e. `handleAuthorizeRequest`) and display your own "accept authorization" form, you should be good to go.
