### ISSUE TITLE
JWT does not use access_lifetime config value

### ISSUE THREAD

**Issue by Arany** [bshaffer/oauth2-server-php#620]
The config value of access_lifetime is not used in the JwtAccessToken when you do not set your own JwtAccessTokenResponseType.

**Comment by bshaffer** [comment]
Can you explain a little more about the issue you're having?

I looked at the code, and the $config parameters seem to be passed correctly. Can you provide a sample of the working and non-working code, or identify where the problem occurs?

**Comment by Arany** [comment]
Hey there,

I can see that this is apparently fixed with this commit  d00a4002f11157b9198a5e5dca077a7d0fb58302 in master (access_lifetime was missing in createDefaultJwtAccessTokenResponseType).
I am using composer to have thi library up to date, so probably there is an old version still in composer.

**Comment by bshaffer** [comment]
Oh yes, looks like it's not in a tagged version yet. I would suggest updating to `dev-develop`, or just continue nagging me until I tag the next release.

**Comment by quintonparker** [comment]
Hey all

I too created a PR for this issue some weeks ago and it was merged into develop branch if I recall correctly

**Comment by andriysilka** [comment]
Could you pls add that PR to next tag?
Thanks

**Comment by bshaffer** [comment]
@andriysilka thanks for the nudge, [tag v1.8.0](https://github.com/bshaffer/oauth2-server-php/releases/tag/v1.8.0) has been created. Please update your libraries accordingly!

**Comment by quintonparker** [comment]
Awesome. Thanks 😁

**Comment by andriysilka** [comment]
Thanks!
