### ISSUE TITLE
Best way to update dynamoDb adapter?

### ISSUE THREAD

**Issue by iam-merlin** [bshaffer/oauth2-server-php#624]
Hi,
Aws sdk is at the version 3.x and the DynamoDb class only support < 3.* (I think you are working on ;) ).

I'm not an expert with the SDK but it seems that the only problem come from "formatAttribute" that has been removed in 3.x.

How do you see the move from 2.8 to 3.x? a new adapter with the necessary update?

**Comment by iam-merlin** [comment]
First draft, need to add test and use it a little more : https://github.com/eoko/oauth2-adapter-dynamodb

**Comment by iam-merlin** [comment]
@bshaffer ping, any idea?

**Comment by bshaffer** [comment]
Hey @iam-merlin sorry for the delay

The best way would be for you to fork this repository and submit a PR. If it's possible for our adapter to support both 2.x and 3.x, that would be the best way (we are using dependency injection for the actual class, so we should be able to execute different logic, depending)

What do you think?

**Comment by iam-merlin** [comment]
Hi @bshaffer , nice to hear you :D.

After thinking a little... that's gonna be hard to include this v3 (or improved the actual class) in you repository nicely. The main (and only reason) is the aws-sdk... there is 2 versions and you actually suggest only "aws-sdk-php". If we add this one, we'll have to create a very long description in `composer.json` or in documentation to explain how to use this adapter specifically v3 (my point of view).

Using composer, this can be interesting to explode all adapter storage to different project? This will simplify the codebase, all unit test and with a simple require every dependencies needed will be directly include, developers will be able to choose a specific version (aws will create a v4, google same etc.)... 

so, What do you think (it's a little about the philosophy of the project with adapters ^^)  ? :p 

(By the way; really nice project + work)

**Comment by bshaffer** [comment]
If you write an adapter I will definitely add it to the docs. It does seem like a better model to include these separately, so they can be versioned along with their dependencies. 

However, to simplify things for the user, if a small change will make the existing class compatible with both, I will be going that route.

**Comment by parallelaus** [comment]
Any update on this issue? Is it now possible to use AWS SDK 3.x ?
