### ISSUE TITLE
Authenticating my Web application users using username/password and then JWT

### ISSUE THREAD

**Issue by danr1979** [bshaffer/oauth2-server-php#630]
Hi.

I have a Web application written in EmberJS that calls an API for its data requirements.  I'm looking to authenticate my Web application users by having them submit a username and password and be given a JWT in return.  Then, each time they try to access a page within the application the JWT will be sent in the request to the API in order to determine if they have permission to access the resource they are requesting.

I've read through the documentation for the oauth2-server-php library but I'm still a little confused as to how to implement my authorisation mechanism.  It looks like I'd want to use the "User Credentials" grant type to get the initial token when they submit their username and password but then for subsequent requests I'd need the "JWT Bearer" grant to check that their JWT is valid.  Is this correct?  Also, it seems that the "User Credentials" grant returns a standard token rather than a JWT so how would I go about changing this so that a JWT is returned instead?

Any help you can offer would be gratefully received.

Thanks.

**Comment by phindmarsh** [comment]
You are certainly on the right track, I have an AngularJS application that uses the same pattern (except the JWT is actually checked by a different app). As I understand it though the JWT Bearer grant is for a different thing. 

The [JWT Access Token](http://bshaffer.github.io/oauth2-server-php-docs/overview/jwt-access-tokens/) docs are really useful (which I'm sure you have already read), but the token will be verified automatically if you configure your server to use JWT Access Tokens, or you can do it yourself with whatever library/code you like. The `firebase/jwt` lib (which is bundled with this lib) has a `decode` method that makes this really easy.

Does that help?

**Comment by danr1979** [comment]
Thanks for your swift response! 

So, I handle the username/password authentication manually using my own code & use either this library or another to generate the jwt. Then, once the jwt has been returned to the requestor they can submit that in subsequent requests & this library can verify them using the jwt bearer grant?

Is that right?

Thanks.

**Comment by phindmarsh** [comment]
Nope, you were correct before when you suggested the user credentials grant type (`grant_type=password`). This is effectively just posting the users username/email and password to the `/token` endpoint and you'll get an access token back. If you have configured the server to use JWT Access Tokens then you _should_ just get one automatically.

From there, you can treat the JWT as a normal token in your Ember app, and then either decode it using this lib or, if your API is a different app, with whatever JWT lib you like.

**Comment by danr1979** [comment]
OK understood. Thanks.

**Comment by phindmarsh** [comment]
Hey @danr1979 did you get this solved? If you did just close off this issue :smile:

**Comment by danr1979** [comment]
Yep, thanks for your help.
