### ISSUE TITLE
IEFT Draft version

### ISSUE THREAD

**Issue by oytuntez** [bshaffer/oauth2-server-php#637]
@bshaffer, thanks a lot for the amazing package.

I have a question: do you think you can give an estimation about which draft version this library implemented at the latest? This is the latest draft at the moment: https://tools.ietf.org/html/draft-ietf-oauth-v2-31

**Comment by bshaffer** [comment]
Hello and thank you!
This library implements [RFC6749](https://tools.ietf.org/html/rfc6749), which is the final version of the specification.

**Comment by oytuntez** [comment]
Great, thank you!
