### ISSUE TITLE
Send Authorization code without redirect

### ISSUE THREAD

**Issue by arufian** [bshaffer/oauth2-server-php#638]
I found that $response->send() will make a redirection to the url that stored at redirect_uri.
My client is an app, so I rather want to send a json response than make a redirection.
Is it possible to send a response after get an authorization code without redirect it ?

**Comment by pjebs** [comment]
Yes. Don't call send(). Inspect the properties in $response and create a json response using the info you need.

**Comment by pjebs** [comment]
However you should ALWAYS be allowing the redirect. If you are making an app, perhaps the grant type you want is user credentials. See twitters documentation on xAuth.

**Comment by Spomky** [comment]
The redirect URI for apps is in general `urn:ietf:wg:oauth:2.0:oob` or `http://localhost`.
Have you tried with these URIs?
See https://developers.google.com/identity/protocols/OAuth2InstalledApp.

**Comment by arufian** [comment]
@pjebs Thanks. I'll try that.
@Spomky Thanks. I guess custom URI also the solution for this.
And regarding to google OAuth2, unfortunately our application policies not allowed external resources handling this job.
