### ISSUE TITLE
UserCredentials doesn't follow standard?

### ISSUE THREAD

**Issue by Patroklo** [bshaffer/oauth2-server-php#640]
Probably I'm wrong, but I am trying to implement a call to UserCredentials in which supposedly I have to only send a username and password, but it also is asking for a client and client password. 

In the specification http://tools.ietf.org/html/rfc6749#section-4.3.1 says that you only have o use the user and pass, also in the first example request from here: http://bshaffer.github.io/oauth2-server-php-docs/grant-types/user-credentials/ 

But given that UserCredentials doesn't implement ClientAssertionTypeInterface in the TokenController in line 112 the system will make a call to validate the request with the client, something that in this case it's not required.

**Comment by ssanders** [comment]
I agree. Our server sets client_id to username and client_secret to password to get around this.

**Comment by Patroklo** [comment]
I think it's not a very big change to implement ClientAssertionblah in that library or, if that breaks backwards code, adding a new grant that does so. 

But let's better wait for some module developer, probably there's something wrong in my understanding.

**Comment by Patroklo** [comment]
@ssanders another lame workaround that I have managed to do it's making a clientName and clientPassword as NULL, that way it worked fine, but still had to send empty parameters for those...

**Comment by bshaffer** [comment]
This library assumes that the client will provide just a `client_id` (if the client is public) or a `client_id` and `client_secret` if the client is confidential. There is no anonymous-client User Credential grants allowed. 

What @ssanders is doing sounds like it should be done using the *Client Credentials* grant type, and not the *User Credentials* grant type.

see [this part](http://tools.ietf.org/html/rfc6749#section-4.3.1) of the same section of the spec you mentioned above:
```
   The authorization server MUST:

   o  require client authentication for confidential clients or for any
      client that was issued client credentials (or with other
      authentication requirements),

   o  authenticate the client if client authentication is included,
```

**Comment by bshaffer** [comment]
Note that the following sample request includes *HTTP Basic* Authorization, which is where the client credentials are located.

**Comment by Patroklo** [comment]
But, as I read in that text you have pasted, the client authentication would be only required if the client is confidential or you pass that credentials, doesn't say anything about making it a required field. 

As I understand (I repeat, probably I'm wrong, but that's what I understand in that specification) what you are doing it's allways counting  the client as a confidential one or requiring that field, but there is also the third option in which you don't  have to use that field in this grant type.

Sorry if I'm annoying, but I'd like to clarify this point.

**Comment by bshaffer** [comment]
Thanks for your research and comments, on behalf of everyone looking for answers to this same question.

It MAY be possible by the spec to allow just `username` and `password` for this grant, but that is not the implementation path taken by this library, as the use cases for this are extremely small. But it should allow for **public** clients, and so only require a `client_id`, as long as the registered client does not have a `secret` assigned.
