### ISSUE TITLE
I think this a question rather then an issue

### ISSUE THREAD

**Issue by Wilt** [bshaffer/oauth2-server-php#644]
I posted this also on [stackoverflow](http://stackoverflow.com/questions/32723198/oauth2-client-id-column-not-allowed-to-be-null).

Why is in the database scheme the `client_secret` column not allowed to be null (`client_secret VARCHAR(80) NOT NULL`)? Is this the common configuration for a valid OAuth database schema?
It is quite common to have public clients that don't need a password. I see that people set an empty string (`''`) in such cases, but a null values seems much cleaner to me.

Is there some special reason to prohibit null values in this case?

**Comment by bshaffer** [comment]
Public clients should still have a client_id, just not a secret. All access
tokens should be tied to a client, so it is known who is accessing Apis on
behalf of the users.

**Comment by Wilt** [comment]
Sorry for this but I made a mistike while writing this. I meant the `client_secret` column not hte `client_id` column. Client secret is declared like this: `client_secret VARCHAR(80) NOT NULL,` so my question remains, why not allow null?

**Comment by bshaffer** [comment]
NULL is fine for client_secret. Feel free to alter the schema, or submit a
pull request to do this.

**Comment by Wilt** [comment]
I added pull requests for this.
Once in the database schema:
https://github.com/bshaffer/oauth2-server-php/pull/645
Two times in the docs:
https://github.com/bshaffer/oauth2-server-php-docs/pull/68
https://github.com/bshaffer/oauth2-server-php-docs/pull/69

**Comment by dsquier** [comment]
@Wilt Good catch. This was something I chose based on my implementation, but as you indicated, was too restrictive. The [DDL repo](https://github.com/dsquier/oauth2-server-php-mysql) has been updated.
