### ISSUE TITLE
example to start integration

### ISSUE THREAD

**Issue by msyadav88** [bshaffer/oauth2-server-php#658]
I have downloaded the whole library, but confuse how to start it with. There are two folders src and test . I just want to know the main index file in which the code of request is . Please guide

**Comment by dschreck** [comment]
I've recently integrated into a project, following docs was simple. Go to http://bshaffer.github.io/oauth2-server-php-docs/ - if you've read all the documentation and have an understanding of how OAuth works you will not be confused.

**Comment by copynpaste** [comment]
Also there is a nice Demo-implementation on https://github.com/bshaffer/oauth2-demo-php.

**Comment by bshaffer** [comment]
Yes, I recommend starting with the [docs link](http://bshaffer.github.io/oauth2-server-php-docs/) (mentioned above) and becoming familiar with the OAuth2 flows using the [demo application](http://brentertainment.com/oauth2/) (also mentioned above), the [code](https://github.com/bshaffer/oauth2-demo-php) for which you can download and run to get started.

This library provides the *bare tools* to build an OAuth2 server. If you want something out-of-the-box, check out [Apigility](https://apigility.org/), which uses this library under the hood.

Thanks guys!

**Comment by msyadav88** [comment]
Actually I want to integrate the oauth2 with the wordpress plugin WP OAuth Server . Is oauth2-server-php the client library or server library ? 
I want a client library from which i can sent request to wordpress plugin and access data from wordpress site.
Please let me know if I am at right direction.

**Comment by copynpaste** [comment]
What do you think why this library is named oauth2-server? Actually WP OAuth Server [is using this library][1] as base.

[1]: https://github.com/justingreerbbi/wordpress-oauth-server#framework

**Comment by bshaffer** [comment]
@msyadav88 yeah this is a client library, not a server library.  Try https://github.com/thephpleague/oauth2-client

**Comment by msyadav88** [comment]
Thanks Brent for your important support,
I have used the oauth2-client setup in my code but any code after including the GenericProvider.php file is not executed( line no 7 in below code). The code stucked on the GenericProvider.php file. I think there is the syntax error of square bracket used in GenericProvider.php as array ( line no 109 )
Please let me know if there is any error in library?

<?php
require_once('config.php');
require_once 'library/class.phpmailer.php';	
error_reporting(E_ALL);
try {
require(PHYSICAL_PATH2.'oauth2-client-master/src/Provider/GenericProvider.php');
echo PHYSICAL_PATH2.'oauth2-client-master/src/Provider/GenericProvider.php'.'dfd';
//require('oauth2-client-master/src/Provider/Exception/IdentityProviderException.php');
define('REDIRECT_URI',$dynamiclink.'/createpage_api2.php');
define('AUTHORIZATION_ENDPOINT',$wordpress_site.'oauth/authorize');
define('TOKEN_ENDPOINT',$wordpress_site.'oauth/token');
$provider = new \League\OAuth2\Client\Provider\GenericProvider(array('clientId' => CLIENT_ID, 'clientSecret'            => CLIENT_SECRET,    'redirectUri'             => REDIRECT_URI,    'urlAuthorize'            => AUTHORIZATION_ENDPOINT,    'urlAccessToken'          => TOKEN_ENDPOINT,    'urlResourceOwnerDetails' => 'http://brentertainment.com/oauth2/lockdin/resource'));

**Comment by bshaffer** [comment]
Sorry, this is not a forum for OAuth2 client debugging. I highly recommend checking out the oauth2 demo (mentioned above).
