### ISSUE TITLE
Google OAuth 2.0 Playground Cookbook

### ISSUE THREAD

**Issue by Kami-no** [bshaffer/oauth2-server-php#659]
Followed the manual https://bshaffer.github.io/oauth2-server-php-docs/cookbook/google-playground/

No redirect after "SUCCESS! Authorization Code:" (Checked with Chrome and Safari).

Also found issues in cookbook:
- scope "basic" should be created

``` sql
insert into oauth_scopes set scope = 'basic';
```
- "redirect_uri" should be right

``` sql
update oauth_clients set redirect_uri = 'https://developers.google.com/oauthplayground';
```
- "state" is required

```
$server->setConfig('enforce_state', false);
```

Checked today with current sources from master branch.

**Comment by Alexanderstephengreenwood** [comment]
Hi Kami-no,

It looks like the implicit grant needs to be set to true also.
I'm struggling on setting the oauth config on that bit... Same with Postman app on Chrome.

Regards,
alex

**Comment by bshaffer** [comment]
This works with my OAuth Demo App if you fill in the following parameters:

- **Authorization Endpoint**: `http://brentertainment.com/oauth2/lockdin/authorize?state=xyz`
- **Token Endpoint**: `http://brentertainment.com/oauth2/lockdin/token`
- **OAuth Client ID**: `demoapp`
- **OAuth Client Secret**: `demopass`
- For *Input your own scopes* enter `openid`
- When it asks for a resource URL, for some reason it isn't finding the `Authorization` header sent by google (I don't know why!!) so you need to add it to the querystring of the resource request: `http://brentertainment.com/oauth2/lockdin/resource?access_token=YOUR_ACCESS_TOKEN`

@Alexanderstephengreenwood setting Implicit to true should not be required for server side! You've probably accidentally set the dropdown to "Client Side"

I hope this helps!

**Comment by bshaffer** [comment]
Thank you for the instructions @Kami-no, I will update the cookbook to reflect this.
