### ISSUE TITLE
Token expiration time measured in server timezone

### ISSUE THREAD

**Issue by afilippov1985** [bshaffer/oauth2-server-php#669]
Token expiration time (and all other times) must be in UTC.

OAuth2\OpenID\ResponseType\IdToken
```
$token = array(
            'iss'        => $this->config['issuer'],
            'sub'        => $user_id,
            'aud'        => $client_id,
            'iat'        => time(),    //    <-----  time from 1970-01-01 00:00:00 in current timezone
            'exp'        => time() + $this->config['id_lifetime'],
            'auth_time'  => $auth_time,
        );
 
```

**Comment by afilippov1985** [comment]
A possible solution is to add `date_default_timezone_set('UTC')` in `OAuth2\Server` constructor.

**Comment by Spomky** [comment]
No, you should not change the default timezone as it could break the application.
A better way should be to always get the timestamp at `UTC+0`:

```php
$timestamp = time() - date('Z');
```

**Comment by bshaffer** [comment]
This is confusing to me - timestamps are timezone-agnostic. As long as the server's time is correct, it shouldn't matter what the timezone is set to, the result of `time` will be the same. All of them are the same amount of seconds from the Epoch (00:00:00 UTC, Thursday, 1 January 1970)...

**Comment by afilippov1985** [comment]
I was wrong.
`time()` return time in UTC.
And expiration checking works fine.
But, when saving to MySQL, __`date()` function converts time to current timezone__.
Then MySQL converts TIMESTAMP values from the current time zone to UTC for storage, and back from UTC to the current time zone for retrieval.
So MySQL shows TIMESTAMPs in current time and it confused me.
Sorry.

**Comment by afilippov1985** [comment]
Related to issue #570
