### ISSUE TITLE
Can't inherit abstract function in  php5.2-develop branch.

### ISSUE THREAD

**Issue by afzal273** [bshaffer/oauth2-server-php#671]
I looked at https://github.com/bshaffer/oauth2-server-php/issues/161 and it said to use the php5.2-develop branch. Despite using that branch I'm still getting this error - 

Can't inherit abstract function OAuth2\Storage\AuthorizationCodeInterface::setAuthorizationCode() (previously declared abstract in OAuth2\OpenID\Storage\AuthorizationCodeInterface) in /my-oauth2-walkthrough/oauth2-server-php-develop/src/OAuth2/OpenID/Storage/AuthorizationCodeInterface.php on line 14

The php version I'm using is PHP 5.3.3 (cli) (built: Oct 23 2014 06:58:46)

**Comment by bshaffer** [comment]
You must not actually be on the branch. The class you've mentioned above doesn't exist in the 5.2-develop branch, as it includes namespaces, which aren't available in php 5.2.

The class above is [here](https://github.com/bshaffer/oauth2-server-php/blob/php5.2-develop/src/OAuth2/Storage/AuthorizationCodeInterface.php), and as you can see is different from the one mentioned in your error. Double check that you're on the right branch.
