### ISSUE TITLE
Revoke token always returns true

### ISSUE THREAD

**Issue by DaCardinal** [bshaffer/oauth2-server-php#674]
I realized the revoke token always returned true even if the access_token or refresh_token doesn't exist in the database. I did a bit of digging and found that it was coming from the Storage class. Particularly:
```php
public function unsetAccessToken($access_token) {
        $stmt = $this->db->prepare(sprintf('DELETE FROM %s WHERE access_token = :access_token', $this->config['access_token_table']));
        
        return $stmt->execute(compact('access_token'));
    }
```

Should I just change the sql statement to check if the code exists before trying to delete or is this a know bug?

**Comment by bshaffer** [comment]
@DaCardinal good catch! that sounds like a great idea.

**Comment by bshaffer** [comment]
also we need to add a test so we can catch if this issue exists in the other storage classes.

**Comment by DaCardinal** [comment]
@bshaffer I made edits to fix this on the PDO storage would try and do a Pull request. Need to add tests too haven't tried the other storages

**Comment by afilippov1985** [comment]
I disagree with this. Unsetting of the non-existent variable is OK. PHP don't throw any error if you unset non-existent variable.
This method should return result of the command execution by the storage driver, and not the result of unsetting.

**Comment by bshaffer** [comment]
Hmm, this is a good point, this is WAD.
