### ISSUE TITLE
Question regarding Token Controller

### ISSUE THREAD

**Issue by Jiekai** [bshaffer/oauth2-server-php#679]
Hi Brian, I tried implementing your OAuth2 solution but on creating the Token Controller, I get this error whenever I run it:

Warning: require_once(oauth2-server-php/src/OAuth2/Autoloader.php): failed to open stream: No such file or directory in /var/www/html/oauth2-server-php/server.php on line 16

Fatal error: require_once(): Failed opening required 'oauth2-server-php/src/OAuth2/Autoloader.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/oauth2-server-php/server.php on line 16

Any idea what's causing this to happen?

**Comment by bshaffer** [comment]
Looks like you were able to solve this issue?
It is recommended you use composer instead of the built-in autoloader.

**Comment by Jiekai** [comment]
Hey Brent,
I solved it. Turns out it was a simple directory error.

Date: Tue, 8 Dec 2015 13:16:42 -0800
