### ISSUE TITLE
the way to clear all expired tokens?

### ISSUE THREAD

**Issue by yuql** [bshaffer/oauth2-server-php#680]
I found expired access_token and refresh_token still in my database.
so , I shoud create a cron job for clean this ?  or clear it in request probabilistic ?

By the way ,@bshaffer
Is there a plan to update the php5.2-develop to master ?

Thanks.

**Comment by copynpaste** [comment]
How or when to clean tokens is on your site/your decision. But on request it may take longer to respond.

Php 5.2 is outdated for about 5 years (http://php.net/eol.php), nobody should support that old version.

**Comment by yuql** [comment]
I get it.
Thanks.
