### ISSUE TITLE
Branch

### ISSUE THREAD

**Issue by pjebs** [bshaffer/oauth2-server-php#683]
Can someone tell me the difference between the:
develop
master
v2.x

Also what caused v2 to be developed? Is it ready for use?
What branch does composer use?

**Comment by bshaffer** [comment]
`develop` is where all changes are merged originally.

`master` is the stable branch, and the tags come from there. It isn't really necessary now that we use semantic versioning, but that was the original purpose.

`v2.x` is for backwards-compatibility breaking changes.

For composer, you can use `dev-develop` if you want all latest changes and `dev-master` if you want the latest stable changes. Don't use `v2.x` yet.  But as [the docs](http://bshaffer.github.io/oauth2-server-php-docs/) state, you should just use `composer.phar require bshaffer/oauth2-server-php "~1.8"`
