### ISSUE TITLE
User Registertion witg Oauth

### ISSUE THREAD

**Issue by sajumani** [bshaffer/oauth2-server-php#688]
Hi,

Am using user credential access_type but i have not found any documentation regarding registration.

Could you please suggest something for this ..??

**Comment by bshaffer** [comment]
You are expected to handle your user registration outside of this library. There are many libraries that do this, most of them particular to a given framework. 

Most of the storages have a [`setUser`](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/Storage/Pdo.php#L328) method also, so you could create your own registration form and call this method to register your users.
