### ISSUE TITLE
Server handleTokenRequest is always returning null

### ISSUE THREAD

**Issue by BrandonShega** [bshaffer/oauth2-server-php#691]
Following along with the tutorial I am calling

```php
if (!$this->server->handleTokenRequest(OAuth2\Request::createFromGlobals(), new WCResponse())->send()) {
     die;
}
```

`WCResponse` is a custom class I made that implements the `ResponseInterface`

For some reason though the `handleTokenRequest` method is always returning null, I can step through it and see that the response is indeed not null but I can never get this to not hit the `die`.

Any ideas? Also if something else needs to be explained, please let me know.

Thanks,
Brandon

**Comment by BrandonShega** [comment]
Never mind, I think it was the `send()` that was getting called, I will just send an error if there is one.

**Comment by bshaffer** [comment]
The `ResponseInterface` is returned, but then you call `send` on it, which does not have a return value
