### ISSUE TITLE
Change default Access Token expiration date

### ISSUE THREAD

**Issue by SimonTheEngineer** [bshaffer/oauth2-server-php#699]
Hi,

Sorry if this has been posted before, couldn't find anything searching..

I want to increase the length of user credential access tokens from 1 hour to 1 day. Refresh token are fine, I believe they're 2 weeks by default?

Thank you!

**Comment by afilippov1985** [comment]
Set `access_lifetime` parameter in server config

```php
$config = array(
    'access_lifetime' => 86400
);
$server = new OAuth2\Server($storage, $config);
```

**Comment by SimonTheEngineer** [comment]
Perfect, thanks very much!

**Comment by wisnugufad** [comment]
this solution is not work in my program ? can you help me?
