### ISSUE TITLE
Unauthorized 401 - after deploying to the server

### ISSUE THREAD

**Issue by gradosevic** [bshaffer/oauth2-server-php#706]
I've configured the oauth2 server locally, but after publishing to my main server, I get 401 error when I try to access it. I successfully get an auth token, it's stored in DB, but when I use it I get 401. Code is unchanged, the only difference is in domain name. Any ideas what could be wrong or how to deeper investigate this issue? Thanks.

**Comment by gradosevic** [comment]
I have resolved this issue. The problem was that authentication header was received as "null" on server. To fix it, I've added this to my .htaccess file:
```apacheconf
<IfModule mod_rewrite.c>
    RewriteEngine On

    RewriteCond %{HTTP:Authorization} ^(.*)
    RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
</IfModule>
```

**Comment by chrismatchett** [comment]
Thanks gradosevic for finding this needle in a haystack. I had the same issue when I moved my oauth2 server to another host.

Chris
