### ISSUE TITLE
Is it possible to log a user in without using POST?

### ISSUE THREAD

**Issue by BrandonShega** [bshaffer/oauth2-server-php#710]
Hi all!

I'm not really sure how to word this question so I did as best I could.

Basically we are allowing users to login to our app with Facebook so we pass to our server their first name, last name, uid and access token where we manually create an account for them.  But we also need to generate an access token to pass back to them to make API calls.

Is is possible to create a custom request that is not based on POST or is there another way to do it?

What I'm referring to is 
```php
$response = $this->server->handleTokenRequest(OAuth2\Request::createFromGlobals(), new WCResponse());
```

If I'm not being clear or you have any other questions, please let me know.

Thanks in advance,
Brandon

**Comment by bshaffer** [comment]
According to the OAuth2 spec, any access token requests to the `/token` endpoint need to be `POST`. 

If you want to do something different, just make the POST request on the backend, or generate the token manually (using [AccessToken::createAccessToken](https://github.com/bshaffer/oauth2-server-php/blob/40e2e32786a76463b721e84d1ee7e7959abcd7c0/src/OAuth2/ResponseType/AccessToken.php#L75):

```php
$tokenResponseType = $server->getResponseType('token');
$accessToken = $tokenResponseType->createAccessToken($clientId, $userId, $scope);
```

**Comment by BrandonShega** [comment]
Sorry to bring this up again, when I run the first line `$tokenResponseType` is empty and then the second line says that I'm trying to call a function on a non-object.  Is there something that needs to be set up ahead of time for this?

**Comment by ssanders** [comment]
We did this to accommodate some users and ended up just putting this at the top of our server.php:
```php
if ($_GET) {
	
	$_POST = $_GET;
	$_GET  = array();

	$_SERVER['CONTENT_TYPE']   = 'application/x-www-form-urlencoded';
	$_SERVER['REQUEST_METHOD'] = 'POST';
}

if ($HTTP_RAW_POST_DATA) {
	
	$post = explode('&', $HTTP_RAW_POST_DATA);
	
	foreach ($post as $k => $v) {
		
		$parts = explode('=', $v);
		
		$_POST[$parts[0]] = $parts[1];
	}
	
	$HTTP_RAW_POST_DATA = '';
	
	$_SERVER['CONTENT_TYPE']   = 'application/x-www-form-urlencoded';
	$_SERVER['REQUEST_METHOD'] = 'POST';
}
```

**Comment by BrandonShega** [comment]
Ya it's more of if the user is logging in with Facebook, they don't have a username/password so I need to be able to manually generate an access and refresh token to be able to pass back to the app to make API calls with.

**Comment by mervick** [comment]
It works using this code

```php
    /** @var \OAuth2\Server $server */
    /** @var \OAuth2\Storage\PDO $storage */
    $storage = $server->getStorage('access_token');
    $refreshStorage = $server->getStorage('refresh_token');
    $config = [
        'token_type' => $server->getConfig('token_type', 'Bearer'),
        'access_lifetime' => $server->getConfig('access_lifetime'),
    ];

    $token = new \OAuth2\ResponseType\AccessToken($storage, $refreshStorage, $config);
    $accessToken = $token->createAccessToken($clientId, $userId);

    print_r($accessToken);

```
