### ISSUE TITLE
Enhancement: Store hashed client_secret rather than txt

### ISSUE THREAD

**Issue by CameronGo** [bshaffer/oauth2-server-php#720]
I don't know if this is already possible and I've missed it, but I think it would be ideal to store a hash of the client_secret rather than the text to improve security of the solution.  The same would also be true of the users.password field.

If I have missed this capability in the existing code please let me know.

**Comment by bshaffer** [comment]
The users passwords [are being hashed](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/Storage/Pdo.php#L313), but this should be implemented in a more secure way in most applications, and don't want this library to handle that.

The `client_secret` in most APIs is recoverable so they can be displayed in the UI.  I would suggest overriding the `setClientCredentials` and [`checkClientCredentials`](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/Storage/ClientCredentialsInterface.php#L30) methods in your storage object if you'd like to hash it.

**Comment by CameronGo** [comment]
Sorry for being dense, but I wanted to confirm: Do you mean I should create my own custom storage object that implements these classes (checkClientCredentials and setClientDetails)?  I didn't see a setClientCredentials and I was also uncertain if there was another way to override the classes you mentioned without creating a custom storage class.  

Thanks in advance, this library has been a huge help so far.

**Comment by bshaffer** [comment]
Hey Cameron! Yes, if you want to hash the client credentials (which, to reiterate, I do not think is necessary since Facebook, Google, etc do not do this), you will want to override your storage class. This is easy to do:

```php
use OAuth2\Storage\Pdo;

class HashClientSecretPdo extends Pdo
{
    public function setClientDetails($client_id, $client_secret = null, $redirect_uri = null, $grant_types = null, $scope = null, $user_id = null)
    {
            $client_secret = $client_secret ? sha1($client_secret) : null;
        }
        return parent::setClientDetails($client_id, $client_secret, $redirect_uri, $grant_types, $scope, $user_id);
    }

    public function checkClientCredentials($client_id, $client_secret = null)
    {
        return parent::checkClientCredentials($client_id, $client_secret ? sha1($client_secret) : null);
    }
}
```

Now pass your new storage class to the server object:

```php
$storage = new HashClientSecretPdo($connection);
$server->addStorage($storage, 'client_credentials');
```

This is a naive implementation, but hopefully this helps.

**Comment by CameronGo** [comment]
Just wanted to leave a note of thanks and also to post the code I implemented in case it is helpful to someone else.  I deviated from the example above in order to use the password_hash and password_verify functions, which do return different results each time the hash is run.  This precludes the ability to check the hash result directly against what is returned from the DB.  

The other thing I implemented here is an additional field in my client_table (client_name) in order to provide a user friendly name for the client that can be displayed on the authorization page, or anywhere else that might end up end-user facing.

namespace OAuth2\Storage;

class HashClientSecretPdo extends Pdo implements ClientCredentialsInterface {
    /* OAuth2\Storage\ClientCredentialsInterface */
    public function checkClientCredentials($client_id, $client_secret = null)
    {
        $stmt = $this->db->prepare(sprintf('SELECT * from %s where client_id = :client_id', $this->config['client_table']));
        $stmt->execute(compact('client_id'));
        $result = $stmt->fetch(\PDO::FETCH_ASSOC);

        // make this extensible
        return $result && password_verify($client_secret, $result['client_secret']);

    }

    public function setClientDetails($client_id, $client_secret = null, $redirect_uri = null, $grant_types = null, $scope = null, $user_id = null, $client_name = null)
    {
        $client_secret = $client_secret ? password_hash($client_secret, PASSWORD_DEFAULT, ['cost' => 12,]) : null;
        // if it exists, update it.
        if ($this->getClientDetails($client_id)) {
            $stmt = $this->db->prepare($sql = sprintf('UPDATE %s SET client_secret=:client_secret, redirect_uri=:redirect_uri, grant_types=:grant_types, scope=:scope, user_id=:user_id, client_name=:client_name where client_id=:client_id', $this->config['client_table']));
        } else {
            $stmt = $this->db->prepare(sprintf('INSERT INTO %s (client_id, client_secret, redirect_uri, grant_types, scope, user_id, client_name) VALUES (:client_id, :client_secret, :redirect_uri, :grant_types, :scope, :user_id, :client_name)', $this->config['client_table']));
        }

        return $stmt->execute(compact('client_id', 'client_secret', 'redirect_uri', 'grant_types', 'scope', 'user_id', 'client_name'));
    }
        
}

**Comment by bshaffer** [comment]
Nice work! Thanks for sharing.
