### ISSUE TITLE
always_issue_new_refresh_token config option does not appear to work when passed to server object

### ISSUE THREAD

**Issue by CameronGo** [bshaffer/oauth2-server-php#722]
I was following the instructions here to modify some of the refresh token behavior:
https://bshaffer.github.io/oauth2-server-php-docs/grant-types/refresh-token/

In my testing I was not able to get the option for always_issue_new_refresh_token to function when passing it to the server object.  I was able to get it to function when passing it to the RefreshToken GrantType object instead, so I have a workaround, but thought I'd pass this along in case anyone runs into the same question.

Below is an excerpt my custom server.php in case I've done something wrong that I've missed:

```php
OAuth2\Autoloader::register();
$storage = new OAuth2\Storage\Pdo(array('dsn' => $dsn, 'username' => $username, 'password' => $password));

// Pass a storage object or array of storage objects to the OAuth2 server class
$server = new OAuth2\Server($storage, array(
    'always_issue_new_refresh_token' => true,
    'refresh_token_lifetime'         => 31536000, // the default value is 2419200
));

// Add the "Client Credentials" grant type
$server->addGrantType(new OAuth2\GrantType\ClientCredentials($storage));

// Add the "Authorization Code" grant type
$server->addGrantType(new OAuth2\GrantType\AuthorizationCode($storage));

// Add the "Refresh Token" grant type to allow you to exchange a refresh token for a new access token
$refresh_token_config = array('always_issue_new_refresh_token' => true); //using this config array b/c it did not work as expected when passed to the server object
$server->addGrantType(new OAuth2\GrantType\RefreshToken($storage,$refresh_token_config));
```

**Comment by bshaffer** [comment]
We have an exact test of this being implemented [here](https://github.com/bshaffer/oauth2-server-php/blob/develop/test/OAuth2/ServerTest.php#L362), so unless there's some other bizarre fishiness going on, your original constructor should work as expected.

If you'd like help implementing it correctly, please paste the full non-working code here, with a means of proving the config value is incorrect.

**Comment by bshaffer** [comment]
Closing this issue. Please reopen or file another issue if you'd like to continue this discussion.
