### ISSUE TITLE
Attempting to secure a custom form page with HttpBasic class

### ISSUE THREAD

**Issue by CameronGo** [bshaffer/oauth2-server-php#724]
I decided I wanted to create a custom page to allow 3rd parties to manage their own client credentials.  For now I will create an initial set of credentials and then allow them to sign in with those credentials and update their own clientData (including client_secret, but not client_id).  The first thing I need to do; however, is secure the page behind the HttpBasic authentication for client credentials and I've been chasing my tail on this for a full day, so hoping for an assist.

I can see an instance of the ClientAssertionType is being instantiated in the Server class, but I have not been able to figure out how to access it, so that I can use the validateRequest and getClientId functions.

Attempts to do something like this result in a fatal error attempting to access the protected property Oauth2\Server::$clientAssertionType:

```php
$test = $server->clientAssertionType->validateRequest($request, $response);

I obviously do not want to modify the built in libraries, so is there a good way to do this?

The way I'm doing this today is in a very basic server.php in my root like this from the cookbook:
require_once('../includes/oauth2-server-php/src/OAuth2/Autoloader.php');
OAuth2\Autoloader::register();

$storage = new OAuth2\Storage\Pdo(array('dsn' => $dsn, 'username' => $username, 'password' => $password));

$server = new OAuth2\Server($storage, array(
    'always_issue_new_refresh_token' => true,
    'refresh_token_lifetime'         => 31536000, // the default value is 2419200
));

// Add the "Client Credentials" grant type
$server->addGrantType(new OAuth2\GrantType\ClientCredentials($storage));

// Add the "Authorization Code" grant type
$server->addGrantType(new OAuth2\GrantType\AuthorizationCode($storage));

// Add the "Refresh Token" grant type to allow you to exchange a refresh token for a new access token
$refresh_token_config = array('always_issue_new_refresh_token' => true); 
$server->addGrantType(new OAuth2\GrantType\RefreshToken($storage,$refresh_token_config));

Then I have a script (for now called clients.php) that at the moment just has this non-working code:
// include our OAuth2 Server object
require_once __DIR__.'/server.php';

use OAuth2\ClientAssertionType\HttpBasic;

$request = OAuth2\Request::createFromGlobals();
$response = new OAuth2\Response();

$test = $server->clientAssertionType->validateRequest($request, $response);
```

Once I get the HttpBasic auth working I expect I will be able to use my $storage object setClientDetails and getClientDetails to do the rest.

**Comment by bshaffer** [comment]
use the public getter:

```php
$server->getClientAssertionType();
```

**Comment by CameronGo** [comment]
@bshaffer Won't that just return the ClientAssertionType?  I don't think that will allow me to use the validateRequest function to authenticate the clientID and clientSecret credentials.

**Comment by bshaffer** [comment]
The `validateRequest` function is public, so you will be able to use it. You can also use the `checkClientCredentials` method on your storage object.

```php
$storage = $server->getStorage('client_credentials');
$storage->checkClientCredentials($client_id, $client_secret);
```

**Comment by CameronGo** [comment]
Yeah - I think I was trying to avoid instantiating another ClientAssertionType outside of the server object.  I prob didn't explain that adequately.  I have a solution working, but by doing exactly that.  Not sure how clean this is, but it works.

```php
$request = OAuth2\Request::createFromGlobals();
$response = new OAuth2\Response();
$clientstorage = $server->getStorage('client_credentials');
$clientassertion = new OAuth2\ClientAssertionType\HttpBasic($clientstorage);
$authenticated = $clientassertion->validateRequest($request, $response);

if ($authenticated!==true) {
    exit('The client credentials provided are invalid.'.PHP_EOL);
}

$client_id = $clientAssertionType->getClientId();
$client_details = $clientstorage->getClientDetails($client_id);
```

**Comment by bshaffer** [comment]
If you call `$server->getClientAssertionType()`, you will not be instantiating another object. The code above does that, however. So I suggest using the getter method instead.

**Comment by CameronGo** [comment]
I'm definitely a novice, so I assume I'm just missing something.  I realize now that I think you're saying this will return the actual ClientAssertionType object, whereas I had believed it was simply going to return some sort of value indicating which ClientAssertionType was in use.

If I understand your suggestion, then what I want to do is this:
```php
$request = OAuth2\Request::createFromGlobals();
$response = new OAuth2\Response();
$clientAssertionType = $server->getClientAssertionType();
$authenticated = $clientAssertionType->validateRequest($request, $response);
```
When I modify my code to do this; however, I get the following response:
Fatal error: Call to a member function validateRequest() on a non-object

When I var_dump('$clientAssertionType') it simply outputs null.
