### ISSUE TITLE
Refresh tokens are not removed if no token_type_hint is specified

### ISSUE THREAD

**Issue by CameronGo** [bshaffer/oauth2-server-php#725]
I've done some testing then re-read the RFC to confirm and I believe it is a true statement that, if no token_type_hint is specified, then the provider should check for tokens of both types and revoke any that are found.  In my testing, if no token_type_hint is specified, the provider will revoke any access tokens it finds, but it does not revoke a refresh_token, yet it still returns a true result.

Is this a bug?

**Comment by bshaffer** [comment]
This is definitely a bug. It is a result of a storage class returning `true` even when no token was found.  

See the [AccessToken](https://github.com/bshaffer/oauth2-server-php/blob/125965cd1d35bb85aa4f3c1c1e0a088790c6df31/src/OAuth2/ResponseType/AccessToken.php#L167) class.  If `unsetAccessToken` returns `true`, then `refreshStorage::unsetAccessToken` is not called.

I assume you're using the PDO storage class, which in `unsetAccessToken` returns true [regardless of the result](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/Storage/Pdo.php#L159). We should instead call `$stmt->rowCount()` to determine if anything has been deleted.

**Comment by CameronGo** [comment]
@bshaffer : I decided to circle back and patch this in my code by extending your class.  (I would attempt a fix and pull request to benefit everyone, but I am not great at this and not sure how to build the test cases, etc.)  I have the below code for the PDO class, which I think addresses the issue you highlighted, but I'm not very sure where to implement it with the least impact to the rest of the classes.

Can I just create a new file (customPDO.php) with just the one function like this:

```php
<?php

class customPdo extends Pdo implements AccessTokenInterface {
    public function unsetAccessToken($access_token)
    {
        $stmt = $this->db->prepare(sprintf('DELETE FROM %s WHERE access_token = :access_token', $this->config['access_token_table']));
        $del = $stmt->execute(compact('access_token'));

        return ($del->rowCount() > 0);
    }
}
```

Then include that file, and instantiate it as I would the original Pdo class and use my $storage object for everything the same as I am already?

```php
$storage = new OAuth2\Storage\Pdo(array('dsn' => $dsn, 'username' => $username, 'password' => $password));
```

I apologize for the questions.  I'm OK at hacking stuff together, but still very much a novice.

**Comment by bshaffer** [comment]
this is now fixed by #729

**Comment by CameronGo** [comment]
@bshaffer I apologize in advance for the stupid question, but should i be including your master branch in my project, or this develop branch?

**Comment by bshaffer** [comment]
It's up to you - this change is in the `develop` branch only, as I usually wait a bit before tagging a major release after merging changes. I'll tag a new release in a week or so.

Typically, you want to check out to a stable tag like this to make sure the package doesn't change unless you need it to change:

```bash
composer require bshaffer/oauth2-server-php:1.8
```

But if your project is in active development, feel free to use `develop`:

```bash
composer require bshaffer/oauth2-server-php:dev-develop
```
