### ISSUE TITLE
Lengthen or shorten access token expiration

### ISSUE THREAD

**Issue by isko-algorithm** [bshaffer/oauth2-server-php#728]
Hello!

I am using a client credentials grant type with no refresh token. I would like to know if it is possible to lengthen or shorten the expiration of access tokens, like for example I want to make the access token last for only a few minutes. Is this possible? Thanks!

**Comment by bshaffer** [comment]
Have you tried changing the `access_lifetime` config option in the OAuth Server object?

```php
$config['access_lifetime'] = 300; // 5 minutes
$server = new OAuth2\Server($storage, $config);
```

**Comment by isko-algorithm** [comment]
Oh yes. Actually I've tried this yesterday and it worked. Now is there any way for me to assign a length, say, per client in the clients table?

**Comment by activatedgeek** [comment]
@isko-algorithm I think that might not be directly available. If you want to do that, probably you can create a new `TokenController`. See [http://bshaffer.github.io/oauth2-server-php-docs/overview/controllers/](http://bshaffer.github.io/oauth2-server-php-docs/overview/controllers/) and the source code there after for the signature of the class constructor.

**Comment by isko-algorithm** [comment]
Hmm okay will try to look at this approach. Thanks!
