### ISSUE TITLE
{"error":"invalid_client","error_description":"Client credentials were not found in the headers or body"

### ISSUE THREAD

**Issue by Oluwafemikorede** [bshaffer/oauth2-server-php#742]
Hello,

I am using php curl to make request to my token.php and am getting this error {"error":"invalid_client","error_description":"Client credentials were not found in the headers or body".

Here is my code

$fields = ['grant_type'=>'client_credentials'];
            $url = DIR.'server';

```
        $username='testclient';
        $password='testpass';

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL,$url);
        curl_setopt($ch, CURLOPT_TIMEOUT, 30); //timeout after 30 seconds
        curl_setopt($ch, CURLOPT_RETURNTRANSFER,1);
        curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_ANY);
        curl_setopt($ch, CURLOPT_USERPWD, "$username:$password");
        curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($fields));
        curl_setopt($ch, CURLOPT_POST, true);
        $status_code = curl_getinfo($ch, CURLINFO_HTTP_CODE);   //get status code
        $result=curl_exec ($ch);
        curl_close ($ch);
```

**Comment by bshaffer** [comment]
This is probably a result of [this bug](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/Request.php#L138) 

You can see a fix implemented [here](https://github.com/bshaffer/oauth2-server-httpfoundation-bridge/blob/develop/src/OAuth2/HttpFoundationBridge/Request.php#L77).
