### ISSUE TITLE
False error message for multiple grant types when implicit grant type is not allowed

### ISSUE THREAD

**Issue by VaszkoD** [bshaffer/oauth2-server-php#747]
Hi!

It seems to me, that there is a bug in ```OAuth2\Controller\AuthorizeController::validateAuthorizeRequest()```.
You check if ```$response_type``` is equal to ```self::RESPONSE_TYPE_AUTHORIZATION_CODE```, and if not, you assume that it is ```"implicit"```.
The problem is, that ```$response_type``` can hold multiple response types (separated by spaces, e.g. ```"code id_token"```), and in this case the direct string comparison wont work.

```php
if ($response_type == self::RESPONSE_TYPE_AUTHORIZATION_CODE) {
    ...
} else {
    if (!$this->config['allow_implicit']) {
        $response->setRedirect($this->config['redirect_status_code'], $redirect_uri, $state, 'unsupported_response_type', 'implicit grant type not supported', null);

        return false;
    }
    if (!$this->clientStorage->checkRestrictedGrantType($client_id, 'implicit')) {
        $response->setRedirect($this->config['redirect_status_code'], $redirect_uri, $state, 'unauthorized_client', 'The grant type is unauthorized for this client_id', null);

        return false;
    }
}
```

For example in the demo app when I set ```'allow_implicit' = false``` in the ```OAuth2Server``` instantiation, and after that I try OpenID Connect with the **Authorization Code + ID Token** button, it gives the error message: _Authorization Failed! implicit grant type not supported_.

**Comment by bshaffer** [comment]
Hmm, this is WAD, as receiving an `id_token` is considered part of the *Implicit Flow* according to [the openid spec](http://openid.net/specs/openid-connect-core-1_0.html#Authentication):

> Authentication can follow one of three paths: the Authorization Code Flow (response_type=code), the Implicit Flow (response_type=id_token token or response_type=id_token), or the Hybrid Flow 

So to receive an `id_token`, `allow_implicit` must be true. This is not a bug, although I agree the error message is unclear.
