### ISSUE TITLE
Is there a way to get username based in access_token?

### ISSUE THREAD

**Issue by fabbio204** [bshaffer/oauth2-server-php#753]
I want to get the username from table users by access_token received. Something like: 

$server->getUserInfoController()->getUser();
(I know this funcion does not exist)

Thank you

**Comment by CameronGo** [comment]
@fabbio204 I believe you can get what you need using the existing resource controller.  See these functions: https://bshaffer.github.io/oauth2-server-php-docs/controllers/resource/

This is what we are using in our environment to pass in an access token, and the response you get back should include the client_id and user_id that are associated with the token.  Note: You would see a user_id value for a token of grant type Auth Code.  For a token of grant type client credentials, there would be no user_id, but you would still have a client_id.

**Comment by andrewrusselrenner** [comment]
Hello. I'm sorry to bring this issue again. I've got small problem here with that user_id. In JWT Bearer Grant Type, the user_id is from JWT subject, which is must already recorded in oauth_jwt table, this bring problem to my another endpoint and client app (i don't know how to explain it better). I can't seems to make it work. Any sample I could follow to? thanks in advance. Sorry to bother before.
