### ISSUE TITLE
how to set return json

### ISSUE THREAD

**Issue by zhangjinling** [bshaffer/oauth2-server-php#756]
The response is like this:
`HTTP/1.1 200 OK
Cache-Control: no-store
Pragma:        no-cache

{"access_token":"26be5c8039be60f128b25b8dd1c427918a35bea9","expires_in":86400,"token_type":"Bearer","scope":null,"refresh_token":"0e521307df8154090066abf0299f37fda3ad51f0"}
`
How to get json!

**Comment by zhangjinling** [comment]
$oauthResponse->getResponseBody();?

**Comment by bshaffer** [comment]
Yes, that'll work.
