### ISSUE TITLE
OpenID Connect Documentation Lacking?

### ISSUE THREAD

**Issue by StachuDotNet** [bshaffer/oauth2-server-php#757]
Is there a discovery document for the OpenID Connect implementation?

**Comment by bshaffer** [comment]
We have an [OpenID Connect Overview](http://bshaffer.github.io/oauth2-server-php-docs/overview/openid-connect/) in the docs and it's also part of [the demo](http://brentertainment.com/oauth2/) as well.

**Comment by lordcoste** [comment]
I've read the docs but can't find any reference to the Discovery Document URL. Is it supported?
