### ISSUE TITLE
Insert user_id instead of username in the tokens table

### ISSUE THREAD

**Issue by iNDicat0r** [bshaffer/oauth2-server-php#764]
Hi

I am using the following UserCredential grant type and want to use the primary key id of the users table instead of the username which is supplied during the authentication process..

`	$storage = new OAuth2\Storage\Pdo($capsule->getConnection()->getPdo() , array('user_table' => 'users'));
	$server = new OAuth2\Server($storage , array('refresh_token_lifetime' => 2419200));
	$server->addGrantType(new OAuth2\GrantType\UserCredentials($storage));
	$server->handleTokenRequest(Request::createFromGlobals())->send();
`

Is there any magic out of the box?

**Comment by afilippov1985** [comment]
There is no magic out of the box.
You have to override `OAuth2\Storage\Pdo::getUser()`

```php
<?php
namespace OAuth2\Storage;

class MyPdo extends Pdo
{
    public function getUser($username)
    {
        $stmt = $this->db->prepare($sql = sprintf('SELECT * from %s where id=:username', $this->config['user_table']));
        $stmt->execute(array('username' => $username));

        if (!$userInfo = $stmt->fetch(\PDO::FETCH_ASSOC)) {
            return false;
        }

        // the default behavior is to use "username" as the user_id
        return array_merge(array(
            'user_id' => $username
        ), $userInfo);
    }
}
```
