### ISSUE TITLE
refresh token not bounded to a specific access token ?

### ISSUE THREAD

**Issue by iNDicat0r** [bshaffer/oauth2-server-php#766]
refresh_token seems not to be bounded to the access token which it was generated for. I have noticed this by looking at the refresh_token table which is related using the user_id only.

So lets say user x has got 2 access token of grant_type=password . Technically each token has it's expiration date which i bounded to the refreshtoken. what happen if i want to refresh token 1 ?

**Comment by bshaffer** [comment]
@iNDicat0r when you use the Refresh Token, you receive an entirely new Access Token. There is no concept of refreshing a specific access token, so binding is not necessary.
