### ISSUE TITLE
Missing values in ID token

### ISSUE THREAD

**Issue by ranjitsingh90** [bshaffer/oauth2-server-php#770]
I am trying to use PayPal as IdP, where I can validate the ID Token. I am getting the ID token but there is missing "iat" values.

**Comment by bluebaroncanada** [comment]
You'll probably have to implement a version of your own for PayPal. It's really very simple.  Just copy the code from one of the existing implementations and modify it to suit your needs.  If you come up with something that works, please feel free to make a pull request.  I'm going to close this as "Won't Fix" for now, but if you really feel it should be here and you can convince me with a solid argument, I'll mark it for 2.0 or 3.0 implementation.
