### ISSUE TITLE
mcrypt_create_iv fails on Windows Server with iis

### ISSUE THREAD

**Issue by geirvatt** [bshaffer/oauth2-server-php#780]
When ResponseType\AccessToken's generateAccessToken() calls mcrypt_create_iv, I get a 500 error.

Windows Server version is 6 (Build 6002 service pack 2).
IIS version is 7.0.6000.16386.

**Comment by pjcdawkins** [comment]
The library requires the mcrypt extension. But PR #773 may resolve that

**Comment by bshaffer** [comment]
Upgrading to `dev-develop` should fix this issue.
