### ISSUE TITLE
Custom logic for user credentials

### ISSUE THREAD

**Issue by AAllport** [bshaffer/oauth2-server-php#785]
Slightly confused
How would I go about writing custom logic for the user credentials, if I want to store them in a different way (hashed and salted) in a different table. How should I go about implementing this.
I usually use mysqli, the oauth server is set up on PDO
TIA

**Comment by bshaffer** [comment]
Hi @AAllport !
Check out the docs on [Custom Storage](http://bshaffer.github.io/oauth2-server-php-docs/storage/custom/). If you are using PDO, you should start by extending the [`OAuth2\Storage\PDO`](http://bshaffer.github.io/oauth2-server-php-docs/storage/pdo/) class and overriding the [`checkPassword` and `hashPassword` methods](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/Storage/Pdo.php#L312):

```php
namespace MyApp;

use OAuth2\Storage\PDO;

class MyPDO extends PDO
{
    protected function hashPassword($password)
    {
        // do custom logic for hashing/salting
    }
}
```

And then when you create the server:
```php
$storage = new MyApp\MyPDO($pdo);
$server = new OAuth2\Server($storage);
```
