### ISSUE TITLE
How many "active" tokens for same username/password combination?

### ISSUE THREAD

**Issue by jahrralf** [bshaffer/oauth2-server-php#786]
Hi,

we use the "User Credentials" flow to get tokens, that works very well. Now with the same method an external API wants to connect and I got the following email: "Just a follow up on my email about the tokens.  In running more tests, it seems that I cannot have more than 13 or 14 tokens for a specific username/password combination even if I run a revoke on both the access_token and refresh_token."

How can that be, how can we fix this? Please let me know if you need to see any code...

Thanks and best regards,

Ralf

**Comment by bshaffer** [comment]
Thanks for logging this issue!
There is no restriction for the number of tokens allowed for a specific username/password, so I'm not sure what would cause this. Please get more information from your customer - what is the request/response for this call? Can you duplicate the issue?

**Comment by jahrralf** [comment]
bshaffer, thanks a lot for replying to quickly. I had to find out that we have a kind of "rate limiting" for logging in which allowed only 15 logins in 15 minutes also if successful, that caused the problem. So no issue with your code, it is working very well. :)

**Comment by bshaffer** [comment]
Woohoo! Glad to hear it.
