### ISSUE TITLE
No easy way to customize JWT payload

### ISSUE THREAD

**Issue by svycka** [bshaffer/oauth2-server-php#793]
it is hardcoded here: https://github.com/bshaffer/oauth2-server-php/blob/v1.8.0/src/OAuth2/ResponseType/JwtAccessToken.php#L65-L75
or maybe I am missing something?

**Comment by bkcummins** [comment]
I am customizing the JWT payload by extending the `OAuth2\ResponseType\JwtAccessToken` and `OAuth2\Controller\TokenController` classes which are referenced where you create your OAuth2Server.

My JwtAccessToken extension only uses the createAccessToken method, and this is where you can customize the payload.  

My TokenController extension only uses the grantAccessToken method.

Hope that helps.

**Comment by svycka** [comment]
thanks @bkcummins I understand that it should be possible but would like to customize a bit easier than extending some classes

**Comment by bshaffer** [comment]
@svycka I agree that we need to make this a little easier. Do you have any suggestions? One way would be to provide a callable as a config argument:

```php
$config = [
    'jwt_payload_callable' => function ($client_id, $user_id, $scope = null, $includeRefreshToken = true) { // do encoding },
];

$server = new OAuth2\Server($storage, $config);
```

Another option would be to create a specific protected method for this:

```php
class MyJwtAccessToken extends AccessToken
{
    protected encodeAccessToken($client_id, $user_id, $scope = null, $includeRefreshToken = true)
    {
         // do encoding
    }
}

//...
$server = new OAuth2\Server($storage, $config);
$server->setResponseType(new MyJwtAccessToken, 'access_token');
```

I prefer the second one, but either works for me. Thoughts?

**Comment by svycka** [comment]
@bshaffer I haven't thought much, but your second example seems pretty good. Also no BC break so can be implemented now I think.

**Comment by svycka** [comment]
resolved with https://github.com/bshaffer/oauth2-server-php/pull/795

**Comment by hsiri** [comment]
@bshaffer sorry for hijacking this thread. but can you include this fix in your latest tag?
