### ISSUE TITLE
Change database table names configuration

### ISSUE THREAD

**Issue by timyounes** [bshaffer/oauth2-server-php#796]
Hi, 

I want to ask if it is possible to change database table name configuration in oauth 2 ? Because I want to customize my database table names.

**Comment by bshaffer** [comment]
Yes! You can do this in the `OAuth2\Storage\PDO` class by passing in a different database name to the [`$config` argument](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/Storage/Pdo.php#L35):

```php
$pdo = new OAuth2\Storage\PDO($connection, [
    'client_table' => 'my_custom_table_name',
    'access_token_table' => 'another_custom_table_name',
    // ...
]); 
```

**Comment by timyounes** [comment]
Thanks @bshaffer
