### ISSUE TITLE
JWT payload and returned token data from OAuth2Server differs

### ISSUE THREAD

**Issue by svycka** [bshaffer/oauth2-server-php#797]
simple question why this: https://github.com/bshaffer/oauth2-server-php/blob/v1.9.0/src/OAuth2/Storage/JwtAccessToken.php#L70-L87 

JWT payload:
```json
{
  "id": "52c8b55fe71b4dd91df4b4331557711f59527300",
  "jti": "52c8b55fe71b4dd91df4b4331557711f59527300",
  "iss": "",
  "aud": "farmisandroid",
  "sub": 3,
  "exp": 1484577539,
  "iat": 1484573939,
  "token_type": "bearer",
  "scope": null
}
```
but when I do:
```php
...
$server->verifyResourceRequest($request);
$token = $server->getAccessTokenData($request);
...
```
`$token` would be:
```json
{
  "id": "52c8b55fe71b4dd91df4b4331557711f59527300",
  "jti": "52c8b55fe71b4dd91df4b4331557711f59527300",
  "iss": "",
  "iat": 1484573939,
  "token_type": "bearer",
  "scope": null,
  "client_id": "farmisandroid",
  "expires": 1484577539,
  "user_id": 3
}
```

I don't know what is this 'OAuth2-friendly format' but maybe someone can explain?

@bshaffer is there a reason for this?

**Comment by bshaffer** [comment]
The simple answer is the [standard JWT fields](https://tools.ietf.org/html/rfc7519#section-4.1) are different from the OAuth2 fields, but this library expects OAuth2 fields. So a handful of fields are renamed when this library pulls the tokens from storage.

Is there a bug, or is this more of a "wtf is going on here"?

**Comment by svycka** [comment]
More like wtf at least now. So far havent found any issues. Maybe just a
bit strange that they differs also docs does not say that those  names are
reserved.

On Jan 17, 2017 23:31, "Brent Shaffer" <notifications@github.com> wrote:

The simple answer is the standard JWT fields
<https://tools.ietf.org/html/rfc7519#section-4.1> are different from the
OAuth2 fields, but this library expects OAuth2 fields. So a handful of
fields are renamed when this library pulls the tokens from storage.

Is there a bug, or is this more of a "wtf is going on here"?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bshaffer/oauth2-server-php/issues/797#issuecomment-273306367>,
or mute the thread
