### ISSUE TITLE
how to renew access_token in password grant type

### ISSUE THREAD

**Issue by Listen-WebDev** [bshaffer/oauth2-server-php#800]
Dear all, 

how to renew access token where it expire? 
Scenario: I have a mobile application with login form, my app send username and password to my api and it check if user can login in, it return access_token and save in DB. This token expire after 1 hour.
If i crate a call after 1 hour my api return "invalid token". 

How to check to each call and renew this token for don't break my code working?

any ideas?

Best all!!!

**Comment by svycka** [comment]
@Listen-WebDev  if you use(most likely you do) refresh_token grant then you can issue new access token like this http://bshaffer.github.io/oauth2-server-php-docs/grant-types/refresh-token/

**Comment by Listen-WebDev** [comment]
Hi svycka, thank you

 but i don't understand :(. In first attemp i login in my app and check credentials (username and password) on my DB.  my first call to api is:

curl -u testclient:testpass https://localhost/token.php -d 'grant_type=password&username=<myusername>&password=<mypassword>'

for check user and password with my DB users table i have implemented  UserCredentialsInterface and write two methods:

checkUserCredentials
getUserDetails()

all seem works, my api token endpoint work and return access token (ie: a64ec1a1e5f40ff7a697d67fa44d9556c857608b  with different refresh token) and save all two token in DB in oauth_access_tokens and oauth_refresh_tokens.

So for example immagine to call **after one hour** this

curl https://localhost/resource.php -d 'access_token=a64ec1a1e5f40ff7a697d67fa44d9556c857608b'

at this point my api return Token is expired. How to implement auto renew token in my class to extend time life in case of expired?

sorry but for me is the first time that use outh2 

thx for patience! :)

**Comment by svycka** [comment]
from documentation:
first like you do you login with username and password: 
```
$ curl -u TestClient:TestSecret https://api.mysite.com/token -d 'grant_type=password&username=bshaffer&password=brent123'
```
and get this: 
```
{
    "access_token":"2YotnFZFEjr1zCsicMWpAA",
    "expires_in":3600,
    "token_type": "bearer",
    "scope":null,
    "refresh_token":"tGzv3JOkF0XG5Qx2TlKWIA",
}
```
then after one hour when your access_token expires you have to get new access token so you have two options send username and password or use refresh_token instead. Example from documentation:
```
curl -u TestClient:TestSecret https://api.mysite.com/token -d 'grant_type=refresh_token&refresh_token=tGzv3JOkF0XG5Qx2TlKWIA'
```
response:
```
{"access_token":"03807cb390319329bdf6c777d4dfae9c0d3b3c35","expires_in":3600,"token_type":"bearer","scope":null}
```
here `03807cb390319329bdf6c777d4dfae9c0d3b3c35` is your new access token.

keep in mind that refresh tokens also expire but they live a lot longer. you can change time when they expires throught config `'refresh_token_lifetime'  => 2419200,` also from documentation. 2419200 = 60*60*24*28 is 28 days in seconds

**Comment by Listen-WebDev** [comment]
Thx :) i understand my problem is "How to check expire token time"

fo example in my resource.php (is a test file but imagine to request books list of my online store, in production will i have a resource file for each rest endpoint):

require_once __DIR__.'/server.php';
if (!$server->verifyResourceRequest(OAuth2\Request::createFromGlobals())) {
    echo json_encode(array('success' => false, 'message' => 'Token expired'));
    die;
}

echo json_encode(array('success' => true, 'message' => 'You accessed my APIs!'));

how can i check expire time then request new token with refresh token? (I don't like to store user and password in my app, i can change it then invalidate my credentials)

Thx svycka :)

Best
