### ISSUE TITLE
un-instantiable setClientCredentials on interface

### ISSUE THREAD

**Issue by bramaningds** [bshaffer/oauth2-server-php#802]
Hi, just want to ask. I have an issue with unlisted method setClientDetails in ClientInterface, I found it when run unit test with replace Pdo Storage with custom class which implements ClientInterface. Is this correct or I have wrong to implement the interface?

**Comment by svycka** [comment]
I don't  think this is used by the library and guess this was added as a helper method to add client to storage but this library does not add clients by itself at least I don't know this feature. To sum up you don't have to implement `setClientDetails()` it is not used by the library.

**Comment by bramaningds** [comment]
Closed, since it is not major issue.
