### ISSUE TITLE
Problem with Authorize

### ISSUE THREAD

**Issue by pyrotechnv** [bshaffer/oauth2-server-php#803]
I really appreciate this project, it is going to make working with Amazon's Alexa possible.
Now to my problem, we have 2 instances of this Server on 2 different domains.  One works Great, the other with the same code fails on the last line of authorize.php.  The $Response->send();  does nothing.  I'm just hoping someone else has had this issue and resolved it.  Any help or suggestions are welcome.

**Comment by svycka** [comment]
first you have to find out why. My guess would be some error with database so I would start from enabling error reporting or logging and find out the error first after this I guess everything will be clear.

**Comment by pyrotechnv** [comment]
Thanks for the reply.  We made the problem.  The Authorize.php that was not working had a blank line before to <?php tag, so it sent headers.  Therefore the $Response->send() would not work.  I hope that this can help someone.  B. Shaffer's code made it easy to track down once we looked into it.  Thanks again for and awesome, useful Oauth Server.
