### ISSUE TITLE
HELP HELP Redirection to Redirect URI not working

### ISSUE THREAD

**Issue by andela-oadebayo** [bshaffer/oauth2-server-php#810]
`HTTP/1.1 302 Found Location: www.google.com?code=8111eb7d745c94c98ce4b48539e33e115eea5c7c []`
After i call on the `handleAuthorizeRequest()`  the above is all i get on my screen, no redirection occurs.

Please Help. @bshaffer 

Thanks for your time

**Comment by pjebs** [comment]
Nothing wrong with that. Looks fine.

You'll probably have to set the redirect_uri to something other than google though.

**Comment by pjebs** [comment]
the 302 http status code IS THE REDIRECT. That tells the browser to perform a redirect.

**Comment by pjebs** [comment]
You're probably printing the response on the screen rather than sending the response to the client(ie. browser)

**Comment by andela-oadebayo** [comment]
@pjebs Am i supposed to the the redirect my self or does handleAuthorizeRequest() do that for me

**Comment by andela-oadebayo** [comment]
@pjebs am just testing with google hoping it will redirect to google but it does not and am not printing it on the page

**Comment by andela-oadebayo** [comment]
@pjebs this is the function that handles the form
`public function verify(){
        $this->autoRender = false;

        // get the oauth server (configured in src/OAuth2Demo/Server/Server.php)
        $server = $this->server['oauth_server'];

        // get the oauth response (configured in src/OAuth2Demo/Server/Server.php)
        $response = $this->server['oauth_response'];

        if($this->request->is('post')) {
            $authorized = (bool) $this->request->data['authorize'];
            $user_id = $this->Session->read("student.id");

            return $server->handleAuthorizeRequest($this->server['oauth_request'], $response, $authorized, $user_id);

        }
    }`

**Comment by andela-oadebayo** [comment]
and after that runs all is i see is this
`HTTP/1.1 302 Found Location: http://oncusp.com/ogaboss/campus-credit/users/developer?code=404147cc0507d10fb882f3dd686000a571eccc42 []`

**Comment by bluebaroncanada** [comment]
Did you ever resolve this issue?
