### ISSUE TITLE
MongoDB storage needs convert token to array from BSONDocument

### ISSUE THREAD

**Issue by fernandoigual** [bshaffer/oauth2-server-php#835]
Hi,

Whe I use MongoDB storage I get an error in library chadicus/slim-oauth2-middleware because expects an array instead of a BSONDocument  :

Argument 1 passed to Chadicus\Slim\OAuth2\Middleware\Authorization::setToken() must be of the type array, object given, called in E:\nando\Proyectos\LemonKey\api\vendor\chadicus\slim-oauth2-middleware\src\Authorization.php on line 79

This could be fixed in ResourceController.php:69 casting token to array:

        // allow retrieval of the token
        $this->token = (array)$token;

**Comment by chadicus** [comment]
Construct your mom to client with a typemap which converts all types to arrays.  http://php.net/manual/en/mongodb.persistence.deserialization.php#mongodb.persistence.typemaps

**Comment by chadicus** [comment]
@fernandoigual  I have updated the [MongoDB example](https://github.com/chadicus/slim-oauth2/blob/master/examples/mongodb/index.php#L13) in the slim-oauth2 package. Hopefully, this will help resolve your issue.

**Comment by fernandoigual** [comment]
Perfect! Thank you.
