### ISSUE TITLE
Token revoke

### ISSUE THREAD

**Issue by sajumani** [bshaffer/oauth2-server-php#864]
Hi,

When user request for new token, How can we remove old tokens ??

now it keep increasing DB size.

**Comment by bluebaroncanada** [comment]
You can delete the old ones.  Right now deleting actually deletes the token from the database, but I think it should keep the token, but set a deleted flag, so that you can review a record of issued tokens.  You could create an index if things are slow.  Are you using the PDO connector with MySql?

**Comment by sajumani** [comment]
yes, am using mysql PDO

**Comment by bluebaroncanada** [comment]
Well you can just write a script to clean up tokens every 24h or so.  In doing that, you could also just create an `is_deleted` flag and mark it as deleted.  You would probably want a compound index on `is_deleted` and the primary key.
It's up to you.  Either way will be pretty fast, but if you never need to audit, you can just delete the token.
