### ISSUE TITLE
Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by TomMettam** [bshaffer/oauth2-server-php#871]
Using this module with PHP 7.2 triggers a warning:

'message' => 'count(): Parameter must be an array or an object that implements Countable',
  'file' => 'vendor/bshaffer/oauth2-server-php/src/OAuth2/Server.php',

with package version v1.9.0

**Comment by bshaffer** [comment]
thanks for reporting the issue and providing the fix! You are what makes open source great and I salute you! 🖖
