### ISSUE TITLE
getting empty 401 error

### ISSUE THREAD

**Issue by patchido** [bshaffer/oauth2-server-php#880]
Hi, i'm tryingto implement a rest api with oauth, and i came across https://github.com/pabloroca/slim3-simple-rest-skeleton which uses this oauth server, i know i should try and contact the other guy, and i have tried with no success, his implementaion of this implementation is good, actually i am able to get myself the token, but for some reason when i try and use it the response is an empty 401, what could be causing this?

any ideas? or what i could do to troubleshoot?

`curl -I http://localhost/slim3-simple-rest-skeleton-master/public/books -H "Content-Type: application/json" -H "Authorization: Bearer 28d4a4ed54da0558ace182619c5e083238b31d15"`
>HTTP/1.1 401 Unauthorized
Date: Wed, 18 Oct 2017 03:10:28 GMT
Server: Apache/2.4.27 (Win32) OpenSSL/1.0.2l PHP/7.1.9
X-Powered-By: PHP/7.1.9
WWW-Authenticate: Bearer realm="Service"
Content-Type: application/json

**Comment by patchido** [comment]
giving a follow up on this, i have found out that if i run the php built-in server the code actually works, what could be the difference which makes apache return empty 401 response?

**Comment by bshaffer** [comment]
You could debug this by checking in the slim application [here](https://github.com/pabloroca/slim3-simple-rest-skeleton/blob/master/app/src/Controllers/_Controller_oAuth2.php#L55) and see if the Authorization header exists.

**Comment by patchido** [comment]
I have tried with no luck using the logger, how can i log with monolog the authorization header?

**Comment by patchido** [comment]
solved it by adding `RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]` to my .htaccess

**Comment by bshaffer** [comment]
Nice!! Sorry about the inconvenience, that bug is a true pain.
