### ISSUE TITLE
what happen if refresh token is expired 

### ISSUE THREAD

**Issue by night-cypher** [bshaffer/oauth2-server-php#888]
Hi, i know that the access token need to refresh when the access token is expired in 3600 seconds. But how about refresh token ? how to handle this case if it is expired in 14 days?

**Comment by northern** [comment]
It means that the user needs to re-authenticate to obtain a new access and refresh token. If 14 days is not enough then you might opt to set the refresh token to a longer expiry time.

**Comment by night-cypher** [comment]
@northern do i need to send request to the server to check the expiry date? or i will store the request date + 14 days in the client side?

**Comment by mqy1023** [comment]
> It means that the user needs to re-authenticate to obtain a new access and refresh token. If 14 days is not enough then you might opt to set the refresh token to a longer expiry time.

how? thanks
