### ISSUE TITLE
Table oauth_users missing Primary Key

### ISSUE THREAD

**Issue by rhertogh** [bshaffer/oauth2-server-php#892]
According to the Step-By-Step Walkthrough (https://bshaffer.github.io/oauth2-server-php-docs/cookbook/) the `oauth_users` table is created without primary key.
This causes problems with MySQL group replication (and possibly other use cases where a primary key is required).

Should `username` be the primary key for the `oauth_users` table?

**Comment by bshaffer** [comment]
Hi @rhertogh ! Yes, `username` would be a great primary key.

**Comment by bshaffer** [comment]
Done! Thank you sir.
