### ISSUE TITLE
Server side access token revocation

### ISSUE THREAD

**Issue by nikhil-dhiman** [bshaffer/oauth2-server-php#893]
Hi, 
Is there a way to revoke user access token/refresh token from server itself. 
Basically we want to deal with users who are marked as spammer/fraud. So we want to logout them immediately whenever any event specified them as spammer or fraudster. 
I can do a dirty check by doing at interceptor level, but want to do it by having a cleaner approach.

**Comment by bshaffer** [comment]
There is nothing specifically supported in this library, only that the `user_id` field in the various storage classes can be used to query the tables and remove the tokens.
