### ISSUE TITLE
PHP 5.4 array syntax

### ISSUE THREAD

**Issue by augsteyer** [bshaffer/oauth2-server-php#900]
Was running the code on PHP5.3 and got an error in my logs:
```
[Thu Dec 07 05:19:10 2017] [error] [client 127.0.0.1] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Parse error:  syntax error, unexpected '[' in /var/www/mage1810/lib/Module/cloud-integration-magento-oauth2/vendor/bshaffer/oauth2-server-php/src/OAuth2/Server.php on line 91
```
These are the php5.4 syntax culprits:
```
/**
     * @var array
     */
    protected $grantTypes = [];

    /**
     * @var array
     */
    protected $responseTypes = [];
```
Based on the required composer version of php 5.3.9, I am assuming this is a bug.

**Comment by svycka** [comment]
hmm seems like @bshaffer forgot to remove php 5.3 support in https://github.com/bshaffer/oauth2-server-php/pull/869 not sure what to do now. removing support now will leave old users with a broken latest version that supports php 5.3.

but @augsteyer maybe time to update your php version? php5.3 is almost 4 years is not supported

**Comment by augsteyer** [comment]
I believe this is the only thing that keeps this from being 5.3 compatible. Easier to switch these two to ```= array(); ``` and retain 5.3.9 support, no?
Also, when working with 100k+ merchant systems, it's not that easy to tell everyone to upgrade their php. Merchant's are risk aversive bunch and would rather avoid our plugin than upgrade their system.

**Comment by bshaffer** [comment]
This has been merged into `master`. Thanks for the fix!
