### ISSUE TITLE
With use_jwt_access_tokens=true, token type is lowercase

### ISSUE THREAD

**Issue by SventB** [bshaffer/oauth2-server-php#918]
With configuration "use_jwt_access_tokens" set to "true", the resulting "token_type" is "bearer". Shouldn't it be "Bearer"?

**Comment by hardysim** [comment]
I think this is correct. Even if I cannot find any "specification" on this, it seems that on every RFC concerning OAuth it's used with a capital `B`.

See https://tools.ietf.org/html/rfc6749#section-7.1

**Comment by bshaffer** [comment]
The uppercase `Bearer` is used when forming a header and making a request with a bearer token. You can see this is properly uppercased in [`OAuth2\AccessToken\Bearer`](https://github.com/bshaffer/oauth2-server-php/blob/master/src/OAuth2/TokenType/Bearer.php#L19). The `token_type` identifier in the `AccessToken` response type is a response parameter, and [according to the RFC](https://tools.ietf.org/html/rfc6749#section-5) is **case insensitive**.

**Comment by hardysim** [comment]
> The token_type identifier in the AccessToken response type is a response parameter, and according to the RFC is case insensitive

That's correct but then why not make it use *the same format as when forming a header"? This way nobody gets hurt but a receiver of this JWT can 1:1 use it as the header for a following request.

**Comment by bshaffer** [comment]
@hardysim Since this library has been around a while, I do not want to make a change without a very good reason. I am not confident that "nobody gets hurt", as that change could potentially break backwards compatibility in somebody's implementation (e.g. saving `bearer` to the database and using a case-sensitive query to pull it back out).
