### ISSUE TITLE
composer require zfcampus/zf-oauth2 outputs Dependencies Abandoned

### ISSUE THREAD

**Issue by StoneMorKnight** [bshaffer/oauth2-server-php#945]
When following the suggestion on [Apigility's documentation site](https://apigility.org/documentation/modules/zf-oauth2), I used this command: 
`composer require zfcampus/zf-oauth2`

I received the following output: 
`Using version ^1.5 for zfcampus/zf-oauth2
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package herrera-io/json is abandoned, you should avoid using it. Use kherge/json instead.
Package herrera-io/phar-update is abandoned, you should avoid using it. No replacement was suggested.
Package kherge/version is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files`

Please note the following lines of the output: 
`Package herrera-io/json is abandoned, you should avoid using it. Use kherge/json instead.`
`Package herrera-io/phar-update is abandoned, you should avoid using it. No replacement was suggested.`
`Package kherge/version is abandoned, you should avoid using it. No replacement was suggested.`

I received the same warnings when attempting to install the package directly from bshaffer with the following command: 
`composer require bshaffer/oauth2-server-php "^1.10"`

@bshaffer Is there any plan to update these packages so that they are using up-to-date dependencies?

Since Apigility needs these dependencies as part of the OAuth2 portion of the framework, will this be something that will be updated? Or are the zfcampus/zf-oauth2 and bshaffer/oauth2-server-php packages considered legacy?

**Comment by bshaffer** [comment]
This library does not depend on any other dependencies, so I think you must be seeing that error for existing dependencies in `composer.json` when running `composer require bshaffer/oauth2-server-php`. Try installing this package in an empty directory and it should install as expected.

**Comment by bshaffer** [comment]
In case it wasn't clear, the errors you are seeing are a result of dependencies declared as part of another package. You can confirm this with the `why` command in composer:

```
composer why herrera-io/json
```
