### ISSUE TITLE
Purpose of user_id in the oauth_clients table in the cookbook example

### ISSUE THREAD

**Issue by rlvillacarlos** [bshaffer/oauth2-server-php#946]
I would like to know the purpose of the  `user_id` in the `oauth_clients` table. Is it meant for assigning the user account that owns a client account?

**Comment by bshaffer** [comment]
yes, if you'd like to keep track of the users who created the oauth clients, this is the field to do it. It's not a part of the OAuth2 spec, it's just something I added because I thought it would be useful in most cases.
