### ISSUE TITLE
At line 369 of the vendor / bshaffer / oauth2-server-php / src / OAuth2 / Response.php file has the following code: "$ sep = isset ($ parts ['query']) && count ($ parts ['query']) " and error occurs in count(), because $parts ['query'] is not an array, it's a string.

### ISSUE THREAD

**Issue by julianaEngelmann** [bshaffer/oauth2-server-php#949]
If we go to the site
http://php.net/manual/pt_BR/function.parse-url.php (parse_url function) we can see that the query position is a string. Is it correct to use the count ($parts ['query']) function? Because it is not an array, an error occurs. This is taking effect in the php7 version. In php5 this count is accepted.

**Comment by bshaffer** [comment]
Thank you for finding this!
In PHP 5.x - 7.1 , this will always pass (since `count` returns `1` for all non-array arguments, as far as I can tell). 

In PHP 7.2, this throws an error.

**Comment by bshaffer** [comment]
Fixed in `master`

**Comment by julianaEngelmann** [comment]
Thank you!
