### ISSUE TITLE
How to pass the userid into the process?

### ISSUE THREAD

**Issue by DaveHuff** [bshaffer/oauth2-server-php#958]
We want use the library to facilitate sso. Currently we have logged in users that we wish to authenticate/authorize for external resources. 

The problem is getting the userid into the process. In test the userid was just hardcoded into the authorize.php script. Like this:

$user_id = '5bd0ad6b-12d0-43c6-ab26-7908a2d14985'; // A value on your server that identifies the user

$server->handleAuthorizeRequest($request, $response, $is_authorized, $user_id);

What is the proper way to do this in production? Thanks!

Here is the code in the AuthorizeControllerInterface .php we are most interested in, specifically  
$user_id = $this->somehowDetermineUserId(); 

```
/**
 *  This controller is called when a user should be authorized
 *  by an authorization server.  As OAuth2 does not handle
 *  authorization directly, this controller ensures the request is valid, but
 *  requires the application to determine the value of $is_authorized
 *
 *  @code
 *      $user_id = $this->somehowDetermineUserId(); 
 *      $is_authorized = $this->somehowDetermineUserAuthorization();
 *      $response = new OAuth2\Response();
 *      $authorizeController->handleAuthorizeRequest(
 *          OAuth2\Request::createFromGlobals(),
 *          $response,
 *          $is_authorized,
 *          $user_id
 *      );
 *      $response->send();
 * @endcode
 */
```

**Comment by trahibidadido** [comment]
You store your UserID in token information and retrieve it as follows:
```
$token = $server->getAccessTokenData(OAuth2\Request::createFromGlobals());
$userId = $token['user_id'];
```

**Comment by bdegoy** [comment]
With OpenID Connect, you may call Authorize Endpoint with login_hint parameter set to your UserID.

**Comment by josematheus10** [comment]
> With OpenID Connect, you may call Authorize Endpoint with login_hint parameter set to your UserID. But oauth2-server-php does not take it into account.

how do I get the user_id saved in the oauth_access_tokens table?

**Comment by bdegoy** [comment]
> how do I get the user_id saved in the oauth_access_tokens table?

At the very end of your authorize controler, write : 
`...
$server->handleAuthorizeRequest($request, $response, $is_authorized, $userId);`
$response->send();
die();

**Comment by bdegoy** [comment]
> $user_id = $this->somehowDetermineUserId();

I see 3 possible origin of UserId (sub):
1 - entered by user in login form (in fact, the user enter i.e an email as login and a users table lookup will give the UserId = username),
2 - pre-determined for the application at registering time,
3 - passed by login_hint parameter when calling authorize.

**Comment by josematheus10** [comment]
> > how do I get the user_id saved in the oauth_access_tokens table?
> 
> At the very end of your authorize controler, write :
> `... $server->handleAuthorizeRequest($request, $response, $is_authorized, $userId);`
> $response->send();
> die();

this worked thanks a lot!
