### ISSUE TITLE
Application name and image

### ISSUE THREAD

**Issue by MaxHayman** [bshaffer/oauth2-server-php#959]
Usually Oauth logins show the application name and a logo.

How am I supposed to go about getting these details. I am using the example authorize.php on the documentation.

```
if (empty($_POST)) {
  exit('
<form method="post">
  <label>Do You Authorize TestClient?</label><br />
  <input type="submit" name="authorized" value="yes">
  <input type="submit" name="authorized" value="no">
</form>');
}
```

getClientDetails returns the information in the oauth_clients table, so I can add some fields here which contain the data, but how would I call that from the example scripts?

**Comment by 0ddlyoko** [comment]
The **oauth_clients** table has a **user_id** field, which can easily be linked to another table, like **server** or in your case **client**

**Comment by bshaffer** [comment]
I would suggest adding columns to `oauth2_clients` and returning them from your storage class. If you're using `PDO`, the new fields will automatically return when you call `getClientDetails`
