### ISSUE TITLE
Replace JwtAccessToken class / extend with custom code

### ISSUE THREAD

**Issue by taat** [bshaffer/oauth2-server-php#970]
How can I extend the library to return some more data in JWT Token response?

I see there's a "jwt_extra_payload_callable" option, but it's not much flexible
(eg. I don't have access to Doctrine there).

How can I substiture JwtAccessToken class with my own, extended class?

I'm using Zend Framework 2 (and Zend Framework 3).

**Comment by bshaffer** [comment]
When you create the `OAuth2\Server` object, pass the callable in as part of the `$config` array:

```php
$server = new OAuth2\Server($storage, [
    'jwt_extra_payload_callable' => function ($client_id, $user_id, $scope) use ($doctrine) {
        return ['extra_field' => 'extra_value];
    }
]);
```
