### ISSUE TITLE
Client without any scope has access to all scopes

### ISSUE THREAD

**Issue by tkarlinski** [bshaffer/oauth2-server-php#972]
Hi 
I found a serious mistake.
I have client X without any scopes. When I make request client_credentials with scope Y in url, then I getting token for the scope Y. The scope Y isset in storage but is not associate with client X.

In code https://github.com/bshaffer/oauth2-server-php/blob/5a0c8000d4763b276919e2106f54eddda6bc50fa/src/OAuth2/Controller/TokenController.php#L228 I found strange logic.

More precisely...

When requested scope exist in storage ` if ($requestedScope) ` but `$availableScope` is null and client has not associated scope (this `if ($clientScope = $this->clientStorage->getClientScope($clientId))` return false) then you only verify existence the scope in base. You don't verify association between scope and client.

The analysed code:
```    
        $requestedScope = $this->scopeUtil->getScopeFromRequest($request);
        $availableScope = $grantType->getScope();
        if ($requestedScope) {
            // validate the requested scope
            if ($availableScope) {
                if (!$this->scopeUtil->checkScope($requestedScope, $availableScope)) {
                    $response->setError(400, 'invalid_scope', 'The scope requested is invalid for this request');
                    return null;
                }
            } else {
                // validate the client has access to this scope
                if ($clientScope = $this->clientStorage->getClientScope($clientId)) {
                    if (!$this->scopeUtil->checkScope($requestedScope, $clientScope)) {
                        $response->setError(400, 'invalid_scope', 'The scope requested is invalid for this client');
                        return false;
                    }
                } elseif (!$this->scopeUtil->scopeExists($requestedScope)) {
                    $response->setError(400, 'invalid_scope', 'An unsupported scope was requested');
                    return null;
                }
            }
```

It  looks like, If the client without any scope, then the client has access to all scopes. Is this error? Maybe I don't understand something? Tell me please

**Comment by bshaffer** [comment]
It was intentionally implemented that a client with "no scope" has "every scope". This is just the default behavior of the library. In your application, you can fairly easily make `scope` a required field for clients, thereby preventing this behavior.

I do agree it would have been better to make this: 

```php
                if (!$this->clientStorage->checkScope($clientId, $requestedScope)) {
                    $response->setError(400, 'invalid_scope', 'The scope requested is invalid for this client');

                    return false;
                }
```

Then the behavior of clients with no scopes could be handled in the Client Storage and not in the Token Controller. You can still do this in a hacky way by making `getClientScope` return a nonexistent scope if one doesn't exist on the client, e.g. "no-scope".

I hope this helps!
