### ISSUE TITLE
How to change to my own user table

### ISSUE THREAD

**Issue by ting5875** [bshaffer/oauth2-server-php#983]
I have existing user table and the password is hashed using bcrypt which is different from sha and oauth_users table used.  Can i know is there way to make it?

**Comment by ting5875** [comment]
Found out the solutions

**Comment by Jbithell** [comment]
Is this something you could post here to share with others having the same issue @ting5875?

**Comment by ting5875** [comment]
Hi there, I implemented my own storage class that implements the UserCredentialsInterface.  This allow me to use my own logic.

    App::singleton('oauth2', function() {

        $storage = new OAuth2\Storage\Pdo(array('dsn' => 'mysql:dbname='.env("DB_DATABASE").';host='.env("DB_HOST"), 'username' =>env('DB_USERNAME'), 'password' => env('DB_PASSWORD')));
        $config = array(
            'access_lifetime' => 86400,
            'always_issue_new_refresh_token' => true,
            'allow_implicit' => true,
        );
        $server = new OAuth2\Server($storage, $config);
        $userStorage = new \App\Http\OauthUser();
        $server->addStorage($userStorage, 'user_credentials');

        $server->addGrantType(new OAuth2\GrantType\AuthorizationCode($storage));
        $server->addGrantType(new OAuth2\GrantType\ClientCredentials($storage));
        $server->addGrantType(new OAuth2\GrantType\UserCredentials($userStorage));
        $server->addGrantType(new OAuth2\GrantType\RefreshToken($storage,$config));


        return $server;
    });


And inside my storage OauthUser,

    public function checkUserCredentials($username, $password)
    {
        return Auth::attempt(['username' => strtolower($username), 'password' => $password, 'status_code' => Globals::STATUS_ACTIVE]);
    }

    public function getUserDetails($username)
    {
        return ['user_id' => $username];
    }
